### ISSUE TITLE
di: Provider with useValue doesn't accept const complex data type instances

### ISSUE THREAD

**Issue by frankpepermans** [dart-lang/angular2#10]
In beta 18, declaring a `Provider` with `useValue` currently fails in the angular transfomer if you use an instance of a complex data type.

For example, use the following setup to define a component:

```
class Bar {
   const Bar();
}

@Component(
    selector: 'foo',
    template: '<div></div>',
    providers: const [const Provider(DisplayOptions, useValue: const Bar())]
)
class Foo {
}
```

This throws `Invalid argument(s): Incorrect identifier "const Bar()"`

And the stack trace is:

```
package:angular2/src/transform/common/type_metadata_reader.dart 1357:7   _readIdentifier
package:angular2/src/transform/common/type_metadata_reader.dart 1375:12  _readValue
package:angular2/src/transform/common/type_metadata_reader.dart 1166:20  _readProvider.<fn>
```

**Comment by frankpepermans** [comment]
Current workaround:

use `useFactory` instead of `useValue`, and simply return the const instance in the factory method body

**Comment by matanlurey** [comment]
Could you try this:

```dart
const displayOptions = const Bar();

@Component(
    selector: 'foo',
    template: '<div></div>',
    providers: const [const Provider(DisplayOptions, useValue: displayOptions)]
)
```

It might be slightly less hacky. The current Angular analyzer/compiler is pretty rudimentary, but we have plans to improve it to include full package resolution. Can update on this soon.

**Comment by matanlurey** [comment]
P3 since there is a workaround.

Blocked by https://github.com/dart-lang/angular2/issues/48

**Comment by matanlurey** [comment]
Just an update: this is still blocked by #48. We have some _early_ work done though towards getting the type information we need to actually resolve the value.

**Comment by matanlurey** [comment]
This is now planned for the 4.0 release.

**Comment by matanlurey** [comment]
This is now unblocked, with caveats:

* `useFactory` is still required when the resolved instance uses a private constructor:

```dart
class Foo {
  const Foo();
}

const Provider(Foo, useValue: const Foo()) // OK

class Bar {
  static const instance = const Bar._();

  const Bar._();
}

const Provider(Bar, useValue: Bar.instance) // NOT OK, we only see "Bar._".
```

This isn't something we can solve in the short-term, but it will make providers more useful for public constructors. I'll give an update when folks are able to start using this externally (initially behind a flag, and hopefully the default for `4.0.0`).

**Comment by matanlurey** [comment]
Blocked by https://github.com/dart-lang/angular2/issues/404.

**Comment by matanlurey** [comment]
Closing since it technically has landed.
