### ISSUE TITLE
Deleting an item from a list modifies subsequent DOM siblings

### ISSUE THREAD

**Issue by kulshekhar** [dart-lang/angular2#102]
When an item is deleted from a list and if the list is used in a template via `ngFor`, all the subsequent DOM siblings of the HTML element corresponding to the deleted item are being modified.

Here's an illustration of what's happening (notice the elements being modified in dev tools) : 

![http://i.imgur.com/LY41Dds.gif](http://i.imgur.com/LY41Dds.gif)

What is expected: 

![http://i.imgur.com/NnAPBoP.gif](http://i.imgur.com/NnAPBoP.gif)

Code used:

Component: https://gist.github.com/kulshekhar/e1d7cfb5fc04b4ed6246cedfa3a05dc6
Template: https://gist.github.com/kulshekhar/97b7ae7e7f696a27ff1b3fe25574773e

The rest of the setup was as described in the [QuickStart guide](https://angular.io/docs/dart/latest/quickstart.html)

Angular version used: 2.0.0-beta.22

**Comment by zoechi** [comment]
I think this was fixed in TS with this PR https://github.com/angular/angular/pull/10287

**Comment by kulshekhar** [comment]
> I think this was fixed in TS with this PR angular/angular#10287

I can confirm this. The main issue is [here](https://github.com/dart-lang/angular2/blob/master/lib/src/common/directives/ng_for.dart#L122)

Any change in an item's index is currently processed as a series of removals and additions, causing the removal and insertion of DOM nodes.

**Comment by kulshekhar** [comment]
I've been able to get this working by mimicking some of the changes (across 5 files) from the above mentioned PR.

However, I'm not sure whether or how this would affect any other parts of Angular (even though `pub run test` passes)

How do you suggest I take this forward? Should I submit a PR or should I share the changes in another manner for them to be reviewed?

**Comment by matanlurey** [comment]
PR is totally fine - we'll patch internally, and run against all of our projects - we should catch anything subtle.

**Comment by kulshekhar** [comment]
Fixed by #103
