### ISSUE TITLE
const names like `ROUTER_DIRECTIVES` according Dart style guide

### ISSUE THREAD

**Issue by zoechi** [dart-lang/angular2#106]
Do you plan to fix these names to align them with the Dart style guide (`routerDirectives`)?

In TS they are gone at all (now `RouterModule`)

**Comment by matanlurey** [comment]
I'm closing this to be realistic it's not a priority and nobody plans on working on it as it's a potentially breaking change with very little real-world benefit. Maybe we can revisit in the future when we have some headroom in features.
