### ISSUE TITLE
Support function literals in useFactory Providers

### ISSUE THREAD

**Issue by natebosch** [dart-lang/angular2#108]
Blocked by https://github.com/dart-lang/angular2/issues/48

May still be infeasible after that, but this is worth exploring.

**Comment by matanlurey** [comment]
Not possible: We need all providers to be statically analyzable, i.e. we could never allow

```dart
Function someFunc;
if (value) {
  someFunc = funcA;
} else {
  someFunc = funcB;
}
provide(Token, useFactory: someFunc);
```

**Comment by natebosch** [comment]
Hopefully we'll eventually have const function literals. If that happens it should be possible to use

const Provider(Token, useFactory: (Token arg) => new SomeType(arg));

Will reopen if the language changes to allow this. Not worth keeping open for now.
