### ISSUE TITLE
Add null coalescing operator (??) in template expressions

### ISSUE THREAD

**Issue by mastodon0** [dart-lang/angular2#11]
Dart needs a way to handle null values in template expression like the `||` operator in JS.
The elvis operator (`?.`) doesn't help in situations like `selectedValue != null ? selectedValue : 'no selection'`. 
Since dart got the support for the `??` operator in 1.12, I think it should be a part of template expressions.

(copy of issue https://github.com/angular/angular/issues/6367 in the old project)

**Comment by matanlurey** [comment]
Sounds like a decent idea. We can add it to our triage.

I imagine this isn't a huge priority only because there is a (meh) workaround in the form of the ternary operator and == null check. Definitely worth doing though!

**Comment by mastodon0** [comment]
I tried to implement it myself, you can see it here https://github.com/mastodon0/angular2/tree/operator_if_null
Not quite sure about the naming though.

**Comment by matanlurey** [comment]
@mastodon0: Please send us a PR. We're in the process of updating our `CONTRIBUTING.md` to explain our new sync procedure, but we'll be happy to take your feature!

**Comment by matanlurey** [comment]
Nice, we got this. Thanks @mastodon0!
