### ISSUE TITLE
Proposal: Move IterableDiffer and KeyValue differs into Platform. Remove DifferFactory abstraction.

### ISSUE THREAD

**Issue by ferhatb** [dart-lang/angular2#117]
To improve performance of ngFor and change detection, we'd like to move these out of providers. To roll your own differs (we have not run across a use case yet), you would have to override PlatformRef.createDiffer\* methods going forward.

**Comment by zoechi** [comment]
I haven't found the differs being exported anywhere.
I don't want a different differ for `ngClass` or `ngFor`, I just want to use the existing iterable and keyvalue differs in `ngDoCheck` of my own directives.
