### ISSUE TITLE
Calling isNotEmpty on null list in template of routed-to component results in incomprehensible error message

### ISSUE THREAD

**Issue by leiboldm** [dart-lang/angular2#118]
When you forget to initialize a property that is used in a ngIf statement for a component that's created from a router-outlet, the error message that is thrown is meaningless and doesn't point you towards the actual error at all.

Here is a copy+paste of the error that appears in the chrome console:

js_helper.dart:1729
Uncaught wrapException @ js_helper.dart:1729
call$0 @ async_patch.dart:561
_microtaskLoop @ schedule_microtask.dart:41
dart._startMicrotaskLoop @ schedule_microtask.dart:50
dart._AsyncRun__initializeScheduleImmediate_internalCallback.call$1 @ async_patch.dart:54
call$0 @ js_helper.dart:2409
eval$1 @ isolate_helper.dart:462
_callInIsolate @ isolate_helper.dart:54
dart.invokeClosure @ js_helper.dart:2409
(anonymous function) @ js_helper.dart:2429

Example code that reproduces this issue.
app_component.dart

```
import 'package:angular2/core.dart';
import 'package:angular2/router.dart';
import 'package:quickstart/test_component.dart';

@RouteConfig(const [
    const Route(path: 'test', name: 'Test', component: TestComponent)
])
@Component(
    selector: 'my-app',
    template: '<a [routerLink]="[\'Test\']">go to test</a><router-outlet></router-outlet>',
    directives: const [ROUTER_DIRECTIVES]
)
class AppComponent {}
```

test_component.dart

```
import 'package:angular2/angular2.dart';

@Component(
    selector: 'test-component',
    template: """
    <h1>Test</h1>
    <div *ngIf="myList.isNotEmpty">myList has data</div>
    <input [(ngModel)]="name" placeholder="what's your name"><br>
    Hello, {{ name }}
    """,
    directives: const [NgIf, NgModel]
)
class TestComponent {
  List myList; // This is the bug, this should not be null.  However, error message doesn't indicate this
  String name = "test-name";
}
```

Full example app (run 'pub get; pub serve' after unzipping):
[example.zip](https://github.com/dart-lang/angular2/files/509790/example.zip)

**Comment by matanlurey** [comment]
Thanks for the report. Definitely worth fixing.

**Comment by matanlurey** [comment]
Fixed with our new crash detection.
