### ISSUE TITLE
Abstract classes with external methods fail if they are not declared in the main `web/index.dart` file

### ISSUE THREAD

**Issue by enyo** [dart-lang/angular2#119]
**EDIT**: as @a14n pointed out, the problem is not related to `dart_google_maps` but always happens when a file is imported, that contains a abstract class like this:

```
abstract class _LatLngBounds {
  external factory _LatLngBounds();
}
```

@kulshekhar noted that adding the `@JS()` annotation fixed the problem, but adding this annotation shouldn't be required.

---

Original issue:

This is a bit of a weird issue, and it took me a while to find it. I have first reported it at a14n/dart-google-maps#37 and have created a [very simplistic demo repo](https://github.com/enyo/google_maps_angular) to showcase the problem:

If `dart_google_maps` and `angular2` are both included in a `lib/` file, and the `web/index.dart` file includes that, there are lots of errors like these:

```
[Error from Dart2JS on angular_maps|web/index.dart]:
packages/google_maps/src/core/mvc/mvcobject.dart:19:3:
External method without an implementation.
  external factory _MVCObject();
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**However**, if all code is simply in `web/index.dart` there are no errors.

I'm assuming that this is an issue with the angular2 transformer, but am not sure.

**EDIT**: to reproduce both results, simply clone the demo repo, and run `pub get && pub build` and it will fail with the errors. Then copy the complete code from `lib/app.dart` into `web/index.dart` and it will work.

**Comment by a14n** [comment]
Just had a quick look and it's not specific to `google_maps` package.

The following code works well with `pub build` :

```dart
--- web/index.dart
import 'package:angular2/core.dart';
import 'package:angular2/platform/browser.dart';

abstract class _LatLngBounds {
  external factory _LatLngBounds();
}
@Component(
  selector: 'main-app',
  template: 'foo'
)
class MainApp {}

main() async {
  bootstrap(MainApp);
}
```

but when you split it into 2 files, `pub build` fails with

```
[Error from Dart2JS]:
web/index.dart:4:3:
External method without an implementation.
  external factory _LatLngBounds();
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

```dart
--- web/index.dart
import 'package:angular_maps/app.dart' as app;
main() => app.main();

--- lib/app.dart
import 'package:angular2/core.dart';
import 'package:angular2/platform/browser.dart';

abstract class _LatLngBounds {
  external factory _LatLngBounds();
}
@Component(
  selector: 'main-app',
  template: 'foo'
)
class MainApp {}

main() async {
  bootstrap(MainApp);
}
```

**Comment by kulshekhar** [comment]
@a14n, I'm not sure if this is relevant but your example compiles if `_LatLngBounds` is annotated with `@JS()`

**Comment by a14n** [comment]
@kulshekhar thanks for the info.

However, even if the `@JS()` is not there, `pub build` should fail.

**Comment by a14n** [comment]
@matanlurey I just try to run the above code again with `angular-2.2.0` and the issue is still there. Did you close this issue because you did not reproduce it ?

**Comment by matanlurey** [comment]
This isn't related to Angular Dart unfortunately. We don't do anything specific via dart2js.

**Comment by a14n** [comment]
Sorry I thought it was caused by the angular2 transformer. But by removing it I get the same issue. I will try to reduce this sample and file a bug against sdk.

Thanks.
