### ISSUE TITLE
[bug] Pure pipes treated like impure pipes re. list values

### ISSUE THREAD

**Issue by chalin** [dart-lang/angular2#12]
**Expected/desired behavior**

See the [Flying Heroes (pure pipe)](http://angular-examples.github.io/pipes/#flying-heroes) example:
- Type in a hero name like "Birdman" and hit enter.

Since "can fly" and "mutate array" are selected, a new flying hero will be added to the existing hero list. 

Since a pure pipe is used here, we should see "Birdman" appear in the _All Heroes_ list, but **NOT** the _Heroes who fly_ list. 

This correct behavior was present up until beta.15. No statements can be made about beta.16 and beta.17 because pipes were broken (cf. https://github.com/angular/angular/issues/8258).

**Current behavior**

"Birdman" appears in both lists, as if the pipe were impure.

**Reproduction of the problem**

Instructions are given above.
- **Angular2 Dart version:** beta.18
- **Browser:** tested on Chrome.

cc @kwalrath

**Comment by zoechi** [comment]
That's quite weird. Setting `pure: true` makes it work.
https://github.com/dart-lang/angular2/blob/61a4a504ea06cbad10f45563120a1d1dda4a890b/lib/src/core/metadata/directives.dart#L853
should return `true` in case there were no value passed but somehow this doesn't seem to work.
Some contained pipes also seem to do that even though it shouldn't be necessary
https://github.com/dart-lang/angular2/search?utf8=%E2%9C%93&q=%22pure%3A+true%22

**Comment by matanlurey** [comment]
Just an update: Haven't had the chance to look at this 😢 

This is great issue if anyone in the community is interested in contributing a fix and a test!

**Comment by ntaoo** [comment]
I have taken a quick look at the code around this bug today, and this change can fix it.
https://github.com/ntaoo/angular2/commit/1cafeabc58246b2b3f1a22929756aec250fc0e9c
(I confirm that with this fix, "Flying Heroes (pure pipe)" example works as expected.)

It looks like, at the compilation phase, `_PipeMetadataVisitor` visits pipe metadata and at the time `PipeMetadata`'s constructor is not evaluated.

I'm not sure that it's the right way to fix it and don't write the test yet.
I'm reading the ng2 transformer with interest.
