### ISSUE TITLE
API doc build is broken

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/angular2#126]
The Dart API doc build for angular.io is broken, apparently by this morning's sync to github.

I don't think the cause is f4d856c8be853649a36da0be19f7d7b3925dbf71 (since Patrice tested those) or e10e2b501e246b47dffffe1dfe579039bc562233 (since I tested those). Apparently, we need better testing of doc comments.

For now, @naomiblack is working around this issue by using the b22 version of angular-dart.

@chalin could you please take a look?

/cc @thso

**Comment by kevmoo** [comment]
How we doin' here?

**Comment by thso** [comment]
This was fixed.
