### ISSUE TITLE
Debuggable code, i.e. generate sourcemaps

### ISSUE THREAD

**Issue by buchanae** [dart-lang/angular2#127]
As far as I can tell, sourcemaps are not generated when building angular2-dart projects using the pubspec described by the tutorials. 

If there's a simple way to add sourcemaps to my project's build, that would be great, please let me know. But, maybe this has more to do with the way the angular2 transform/codegen is written.

**Comment by abuchanan** [comment]
I was able to get sourcemaps by adding this to my pubspec.yml
```
- $dart2js:
    sourceMaps: true
```
