### ISSUE TITLE
Deprecating facade/promise.

### ISSUE THREAD

**Issue by ntaoo** [dart-lang/angular2#13]
If it is a good time to deprecate the facades, I would like to do pull request deprecating src/facade/promise.dart and refactoring the related files. 

https://github.com/ntaoo/angular2/commit/d4ec88ce42fd20ab01c906619aeb750abe91dc86

**Comment by matanlurey** [comment]
Yep, this is happening. There are a few other projects such as [Benchpress](https://pub.dartlang.org/packages/benchpress) that rely on some of these facades, so we are patching the projects internally and will be uploading with the facades removed soon.

**Comment by ntaoo** [comment]
Nice. Then I just wait for the upload.

**Comment by matanlurey** [comment]
Good news, this is almost committed internally and should be in the next major sync 👍

**Comment by ntaoo** [comment]
Great. It will be much easier to read the code.

**Comment by matanlurey** [comment]
I think PromiseWrapper is removed now!

https://github.com/dart-lang/angular2/search?utf8=%E2%9C%93&q=PromiseWrapper
