### ISSUE TITLE
Complete the tokenizer

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular2#146]
- [x] ~~Expressions: Can we re-use parts of the Dart analyzer here?~~
- [x] ~~Pipes~~
- [x] Interpolation

/cc @jonahwilliams

**Comment by jonahwilliams** [comment]
w.r.t. Pipes and Expressions:  Both will be inside quoted values, and `|` is a legal operator in Dart.  I think this should be part of 'Expression' syntax and removed from template grammar.

**Comment by matanlurey** [comment]
That makes sense.
