### ISSUE TITLE
window:resize event name is not allowed

### ISSUE THREAD

**Issue by avstudios** [dart-lang/angular2#152]
I have Directive and I want to add listener for ``window:resize`` event.
```
  @HostListener('window:resize')
  void onResize() {
    print('onResize');
  }
```
But it's generating an error in a template. 
The event  is also not working when I'm adding ('window:resize')="onResize($event)" to my element.

**Comment by zoechi** [comment]
See last bullet in https://github.com/dart-lang/angular2/blob/master/CHANGELOG.md#200-beta21

Angular2 for Dart doesn't support global event targets anymore this way. Use `window.onResize.listen...)` instead.

**Comment by avstudios** [comment]
Thanks Günter. I've created WindowRef service to have an access to window object in my directive. It works fine just wondering if there is a better way to do it.

**Comment by zoechi** [comment]
Not sure what you mean with `WindowRef`. `dart:html` is already an abstraction over the DOM, therefore there shouldn't be another abstraction necessary.

**Comment by basarat** [comment]
"window.onResize" : will change detection still work?

**Comment by zoechi** [comment]
I don't think that's a problem in Dart (I know it is in TS in some browsers) worth checking though

**Comment by matanlurey** [comment]
Should work fine in Dart :)
