### ISSUE TITLE
Create good docs or example of how to implement dynamic component loading

### ISSUE THREAD

**Issue by tomaszkubacki** [dart-lang/angular2#155]
DynamicComponent Loader does not seem like a convenient way of loading compoennts dynamically since loadNextToLocation seems ...wired. 

Wouldn't it be much more natural to have API pointing container where you put your child component ?

Maybe there is another more idiomatic way of doing this (eg. ViewContainerRef) ?
Some docs clearly stating how it should be done would be nice.

**Comment by matanlurey** [comment]
Assigning to @ferhatb - can we make a simple example repository for now?

**Comment by matanlurey** [comment]
We have a nice new `load` function that is easier to use.

@kwalrath Is this something we could have an example on our site for?

**Comment by kwalrath** [comment]
Yep. @chalin, feeling inspired?

**Comment by jodinathan** [comment]
hey @chalin, I bet you are terrifically inspired!
please =]

**Comment by chalin** [comment]
Yes :). We're tracking this via the docs repo issue https://github.com/dart-lang/site-webdev/issues/436.

@matanlurey, maybe close this issue since it is a request for documentation and it is tracked elsewhere -- unless this issue request is specifically for an API doc example, but I suspect not.

**Comment by chalin** [comment]
FYI, this will now be tracked via https://github.com/dart-lang/site-webdev/issues/582
