### ISSUE TITLE
Component encapsulation only works with predefined constants

### ISSUE THREAD

**Issue by dentra** [dart-lang/angular2#158]
Using this code does not produces component with native encapsulation:

``` dart
const ViewEncapsulation myEncapsulation = ViewEncapsulation.Native;

@Component(
    selector: 'test-compo',
    encapsulation: myEncapsulation,
    template: '<h1>test</h1>',
)
class TestComponent {
}
```

Is this expected behaviour?

**Comment by matanlurey** [comment]
This is expected behavior because of the naivity of the current component compiler.

It's fixable though, but will is _also_ blocked on https://github.com/dart-lang/angular2/issues/48; I'll keep this open to track. For now, declare it exactly in your definition.

**Comment by matanlurey** [comment]
This is now planned for the 4.0 release.

**Comment by matanlurey** [comment]
Blocked by https://github.com/dart-lang/angular2/issues/404.

**Comment by matanlurey** [comment]
This works as of HEAD, though it is not released yet.
