### ISSUE TITLE
Implicit class name conflicts with 'dart:html'

### ISSUE THREAD

**Issue by Adamovskiy** [dart-lang/angular2#163]
There was class with name `Text` and default constructor in project, and in `2.0.0-beta.17` it was ok, but after update to `2.0.0` (pub version `1.20.1`) it leads to errors like:
```
NoSuchMethodError: incorrect number of arguments passed to method named 'Text'
Receiver: Type: class 'Text'
Tried calling: Text(" ")
Found: Text()
```
When custom class name conflicts with one from `dart:html`, the custom one overrides original, and there is no any compile time error or analyzer warning, runtime exception only:
```
import 'package:angular2/core.dart';

class Text {}

@Component(
    selector: 'my-app',
    template: ' ')
class AppComponent {}
```

**Comment by matanlurey** [comment]
Sorry, but as of right now we require no conflicts with `dart:html`.

In the future it's likely we will use `part` instead of a standalone library, and this will be more clear. Sorry for the confusion.
