### ISSUE TITLE
Binding fails on non-dart events

### ISSUE THREAD

**Issue by pinnisi** [dart-lang/angular2#172]
If I change a property from a non-dart event (for example, a 3rd part js library) binding doesn't work.

Angular: 2.0.0

see following simple example:

import 'dart:html';
import 'dart:js';
import 'package:angular2/core.dart';

@Component(
    selector: 'my-app',
    template: '''<p>Value: {{value}}</p>
    <button #btn1>1</button>
    <button (click)="click2()">2</button>
    <button #btn3>3</button>''')
class AppComponent implements OnInit{
  String value = 'initial';

  @ViewChild('btn1')
  ElementRef btn1;

  @ViewChild('btn3')
  ElementRef btn3;

  click2() {
    value = 'value2'; // works
  }

  @override
  ngOnInit() {
    (btn1.nativeElement as ButtonElement).onClick.listen((_) {
      value = 'value1'; // works
    });

    JsObject jb3 = new JsObject.fromBrowserObject(btn3.nativeElement);

    jb3.callMethod('addEventListener', ['click', (_) {
      value = 'value3'; // doesn't work
    }]);
  }
}

**Comment by pinnisi** [comment]
solved using NgZone

**Comment by kwalrath** [comment]
@pinnisi could you point me to how you used NgZone? Sounds like something we should document...

**Comment by pinnisi** [comment]
I put this property in class:

**final NgZone _zone;**

and this in constructor:

**AppComponent(this._zone)**

then:

JsObject jb3 = new JsObject.fromBrowserObject(btn3.nativeElement);

    jb3.callMethod('addEventListener', ['click', (_) {
      _zone.run(() {
        value = 'value3';
      });
    }]);
