### ISSUE TITLE
Parse expressions into an AST

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular2#174]
## Background

Users in Angular 2 can write a subset of the Dart language as `expressions` in their HTML:

```html
<button *ngIf="showCancel && !isCancelled">
  {{getCancelText()}}
</button>
```

This compiles _almost_ directly as Dart code, with one exception, the `|` operator`.

In Angular, this means `transform` (or `pipe`):

```html
{{ getCancelText() | 'uppercase' }}
```

If we desugared this syntax early, we might be able to use the Dart analyzer directly to do expression parsing, meaning ~anything that is a valid Dart expression would be valid in our Angular template.

## Options

1. Desugar pipes so the analyzer package can be used directly

```html
{{ foo | 'uppercase' }}
```

... would become ...

```dart
uppercase$Pipe.transform(foo)
```

And we could use [parseCompilationUnit](https://www.dartdocs.org/documentation/analyzer/0.29.0/analyzer/parseCompilationUnit.html).

Long term we might want to deprecate the `|` symbol and rely on something like:

```dart
$pipe(foo, 'uppercase')
```

Instead.

2. Use the current expression parser or fork it
3. Create a new expression parser

**Comment by matanlurey** [comment]
/cc @bwilkerson @sigmundch 

Does `1` look like a good idea? We'd like to just support all Dart exprssions

**Comment by scheglov** [comment]
1. Does it mean that `|` (as a bit operation) cannot be used anywhere in Angular expressions?

2. In the old Angular1 support code, written in Java, we scanned expressions and then separated filter sub-expressions (still tokens) by looking through the token stream from the end until we find a `|`. What's left is the expression token stream, plus we have zero or more filter token stream. Each expression token stream can be converted to AST `Expression` using `Parser.parseExpression(Token token)`.

**Comment by matanlurey** [comment]
@scheglov:

1. Today, yes, `|`| cannot be used in expressions. We'd like to fix this in the future, though.

2. Oh neat, that looks like something we could do. /cc @jonahwilliams

**Comment by sigmundch** [comment]
I'd personally lean towards (2) or add some restrictions to the dart expression language by validating what you parse out of (1) to help make templates more maintainable and readable. In particular, some Dart expressions are likely going to be noisy in the context of templates (e.g. cascades and closures with full statement bodies) and some are really indicating that the user is doing more than they should be doing within the context of a template, especially when you are in a binding context and not in an event handler (e.g. assignments, async/await, throwing, and other expressions that seem to have side-effects).

**Comment by matanlurey** [comment]
I'd hope we'd have a non-goal of trying to enforce style/readability of expressions :-/

I agree with you, but being able to re-use the Dart parser will simplify things - unless it's a terrible idea. I'd be OK with being _stricter_ though, for example maybe not allowing closures, cascades, etc (linting them at compile time).

**Comment by bwilkerson** [comment]
From a UX perspective, it's much better to accept and understand a superset of what you want to allow and then to generate errors (hints, lints, etc.) when it's something you don't want to allow.
