### ISSUE TITLE
Template parser should be re-usable to create update/migration scripts

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular2#185]
i.e., we need something like

```dart
var nodes = parse(someHtml);
nodes = doMigration(nodes);
return nodesToHtml(nodes);
```

Where we could perhaps rename all selectors `foo` to `foo-old`, for example.

/cc @jonahwilliams

**Comment by jonahwilliams** [comment]
So we need a  `toDomString()` to convert an AST back into a String, and then some helper methods for changing AstNodes

     var newNode = oldNode.map((name, value, children) {
         if (name == 'something') {
           return new NgElement(...):
         }
         return new NgSomething(...)
     });
