### ISSUE TITLE
problem when with multiple calls to bootstrap

### ISSUE THREAD

**Issue by chalin** [dart-lang/angular2#191]
The [dependency-injection sample (live example)](http://angular-examples.github.io/dependency-injection/) stopped working as of beta.22 (though it does work under beta.21).

To see the problem:
- Click on the "Next User" button in the User section.
- What should happen is that the user should toggle between Alice and Bob (with Alice having appropriate authorization and Bob doesn't).
- What actually happens when clicking the button is ... nothing visible to the user.

I added some trace code and the click event handler is being called, but the view isn't being updated.

The [sample code is here](https://github.com/angular-examples/dependency-injection).

There are two other failures (pipes and template-syntax), but they seem to be related to the same issue (of the view not being refreshed as it should).

**Comment by chalin** [comment]
@matanlurey commented:
> Interesting - it works if I comment out bootstrap(ProvidersComponent) and only bootstrap a single app.

Opening this as a tracker issue.

cc @kwalrath @TedSander

**Comment by matanlurey** [comment]
This is not supported right now, unfortunately. It will have to remain blocked for the time being.

**Comment by chalin** [comment]
Ok, thanks; in this case, I was able to rewrite both failing test cases to avoid multiple invocations of bootstrap.

**Comment by chalin** [comment]
Closing for now.

**Comment by filiph** [comment]
Hi, what is this blocked on? I have indications that this can be a blocker for companies that try to gradually introduce AngularDart. (One such company started adding AngularDart via separate mini-apps -- and they hit this issue on mini-app #2.)

Feel free to close again if there's a workaround.

**Comment by Thiltal** [comment]
Actually we ends up on some JS driven solution:
```
document.write("<ng-root-"+window.easyDartLoaders.length+"></ng-root-"+window.easyDartLoaders.length+">");
  
window.easyDartLoaders.push({
    "plugin": "knowledgeBase",
    "data":  "{'someDataForPlugin':true}")
  })
```

in Dart:

```
List<Loader> loaders = [];
main() async {
  for (JsObject o in (context["easyDartLoaders"] as JsArray)) {
    loaders.add(new Loader.fromJsObject(o));
  }

  for (int i = 0; i < loaders.length; i++) {
    Type component =getComponentToBootstrap(i);
    if(component!=null){
      bootstrap(component);
      loaders[i].index = i;
    }
  }
}

Type getComponentToBootstrap(int i) {
  switch (i) {
    case 0:
      return NgRoot0;
    case 1:
      return NgRoot1;
    default:
      return null;
  }
}

@Component(selector: "ng-root-0",
    template: "<root-switcher [loader]='myLoader'></root-switcher>",
    directives: const [RootSwitcher])
class NgRoot0 {
  Loader get myLoader => loaders[0];
}

@Component(selector: "ng-root-1",
    template: "<root-switcher [loader]='myLoader'></root-switcher>",
    directives: const [RootSwitcher])
class NgRoot1 {
  Loader get myLoader => loaders[1];
}
```

**Comment by matanlurey** [comment]
Is this just a documentation issue? @filiph @ferhatb @kevmoo

**Comment by chalin** [comment]
No, it isn't just a documentation issue.

We _used to_ have doc examples that made **multiple calls to bootstrap**, but those examples stopped working so I [refactored the samples to make a single call to bootstrap](https://github.com/dart-lang/angular2/issues/191#issuecomment-261741480). I haven't recently re-tested mutliple call scenario so I don't know if it works now.

**Comment by matanlurey** [comment]
This isn't a priority at the moment, though I'll leave the issue open for others.
