### ISSUE TITLE
Allow to attach/detach views to ApplicationRef

### ISSUE THREAD

**Issue by zoechi** [dart-lang/angular2#196]
like https://github.com/angular/angular/commit/9f7d32a326b22734a92a09814ff4460e3cd9522c
(https://github.com/angular/angular/issues/9293)

This would be great for components that need to be added outside Angular2 (menu, ...)

**Comment by matanlurey** [comment]
What components are added outside of Angular? @zoechi 

I'm confused how this would even be used.

**Comment by zoechi** [comment]
To be able to freely position all kinds of overlays like menu, dialog, toast...
If you have another good workaround it would be fine as well. I can't claim to have deep CSS knowledge.

**Comment by matanlurey** [comment]
I'll take a look at this, thanks!

**Comment by matanlurey** [comment]
I think with the addition of the `angular2_components` repo/overlays this is obsolete.
