### ISSUE TITLE
RouterLink support parameters of type other than String

### ISSUE THREAD

**Issue by chalin** [dart-lang/angular2#204]
The usual way of specifying a router link is something like:
```
<a [routerLink]="['HeroDetail', {id: hero.id.toString()}]"> ...
```
Dropping the invocation of `toString()` still works when the app is run in unchecked mode. In checked mode, a call to, say, `_routeParams.get('id')` results in a type error because `get()` is declared to return a `String`.

Could we not change the signatures as follows?
```
class RouteParams {
  Map<String, any/*was String*/> params;
  RouteParams(this.params);
  any/*was String*/ get(String param) => params[param];
}
```
This would allow router link specs to be written more succinctly as:
```
[routerLink]="['HeroDetail', {id: hero.id}]"
```

cc @kwalrath @filiph

**Comment by zoechi** [comment]
What is the expected behavior? 
Calling `.toString()` on all arguments that are not passed as string?

**Comment by chalin** [comment]
Well, I see two possibilities, either always invoke `toString()` on non-string parameters, or just call `toString()` if/when needed.

In the latter case, for example, the router link spec would pass in a `hero.id` (an `int`), which the processing component is more than glad to accept as an `int`. (Of course, this would mean that the component would need to be prepared to receive a parameter either as an `int` or a `String`.)

**Comment by zoechi** [comment]
Actually, even though it is sometimes inconvenient I'd prefer the current behavior. 
Route parameters always need to be converted to a string when the URL is created.
I would find it quite surprising if I'd receive other types from `params['xxx']` than string.

**Comment by chalin** [comment]
Gunter, thinking of this more closely, you are probably right. The current scheme is probably the simplest and most consistent. Closing.
