### ISSUE TITLE
Question regarding {map: syntax} in angular templates

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/angular2#206]
Looking at the angular [cheatsheet](https://angular.io/docs/dart/latest/guide/cheatsheet.html), the example code for ngStyle contains a discrepancy with dart semantics/syntax:

```<div [ngClass]="{active: isActive, disabled: isDisabled}">```

In dart code, the expression is not correct. Rather, it has to be `{"active": isActive, "disabled": isDisabled}`. I also confirmed that the example code works correctly (though it also seems like my "correct" code _also_ works correctly).

Is this intentional? It is causing [an issue with the analyzer](https://github.com/dart-lang/angular_analyzer_plugin/issues/78), and also in theory could get in the way of valid dart code such as constructing fancy things such as a `Map<InputElement, String>` in a dart expression.

```
   <input #name ...
   <input #password ...
   <my-component inputs="{name: 'something', password: 'something else'}" ...
```

I believe this would create a `Map<String, String>` instead of a `Map<InputElement, String>`.

We can work around it if its intentional behavior, or too large a breaking change for too little benefit to fix at this point. But thought I'd file this to check first.

**Comment by matanlurey** [comment]
I think the _intentional_ behavior here would be requiring quotes, i.e. "name".
