### ISSUE TITLE
Routing documentation uses Typescript snippets

### ISSUE THREAD

**Issue by kulshekhar** [dart-lang/angular2#210]
AsyncRoute: https://angular.io/docs/dart/latest/api/angular2.router/AsyncRoute-class.html
AuxRoute: https://angular.io/docs/dart/latest/api/angular2.router/AuxRoute-class.html
Route: https://angular.io/docs/dart/latest/api/angular2.router/Route-class.html

**Comment by matanlurey** [comment]
Closed by https://github.com/dart-lang/angular2/issues/211

Thanks!
