### ISSUE TITLE
Classes collision in .template.dart

### ISSUE THREAD

**Issue by Tomucha** [dart-lang/angular2#212]
I have a component with these imports:

    import 'dart:async';
    import 'package:angular2/core.dart';
    import "package:googleapis_auth/auth_browser.dart";
    import 'package:googleapis/drive/v3.dart';

… and template with simple bindings. Compiled template contains:

    import 'package:googleapis/drive/v3.dart';
    ...
    import 'dart:html';
    ...
    var _anchor_12 = new Comment('template bindings={}');

… and that results to:

    NoSuchMethodError: incorrect number of arguments passed to method named 'Comment'
    Receiver: Type: class 'Comment'
    Tried calling: Comment("template bindings={}")
    Found: Comment()

Drive v3 also contains class Comment. Changing imports in my component to:

    import 'dart:async';
    import 'package:angular2/core.dart';
    import "package:googleapis_auth/auth_browser.dart";
    import 'package:googleapis/drive/v3.dart' as d;

… solves the issue. But it took me a while.

**Comment by Tomucha** [comment]
To clarify the last paragraph: Changing imports IN MY COMPONENT to ...

**Comment by Adamovskiy** [comment]
Looks like the problem is same as #163.

**Comment by matanlurey** [comment]
You'll need to import anything that conflicts with `dart:html` with a prefix, for example:

```dart
import 'package:googleapis/drive/v3.dart' as google_drive;
```

Thanks!

**Comment by zoechi** [comment]
I assume you plan to change generated code so that it always uses prefixes, so that custom code doesn't need to.
