### ISSUE TITLE
Static class members don't work in `useValue` providers

### ISSUE THREAD

**Issue by natebosch** [dart-lang/angular2#218]
When creating a Provider it does not work to have `useValue: SomeClass.staticMember`.

The transformer is failing at [this line](https://github.com/dart-lang/angular2/blob/3c4658dfc8a8a9a4a0e46a42880bda650fed7a9d/lib/src/transform/common/type_metadata_reader.dart#L1317). The expression `SomeClass.staticMember` shows up as a `PrefixedIdentifier` and since it starts with a capital letter it is not allowed.

If static class members aren't allowed here the error message should be more clear and suggest a workaround. If we intend to allow static class members we won't be able to use a check against a capital letter.

One workaround available is to create a new top-level variable.

```
const someVariable = SomeClass.staticMember;
const Provider(someToken, useValue: someVariable);
```

**Comment by matanlurey** [comment]
This is now planned for the 4.0 release.

**Comment by matanlurey** [comment]
Actually, mostly a duplicate of https://github.com/dart-lang/angular2/issues/10.
