### ISSUE TITLE
Forms documentation

### ISSUE THREAD

**Issue by afpatmin** [dart-lang/angular2#219]
The [forms guide](https://angular.io/docs/dart/latest/guide/forms.html) on Angular.io seems a bit outdated, for example it uses the newly deprecated NgControlStatus.

Also, I can't get the example to work on the latest angular build (2.1.1), the ngControl directive doesn't seem to register at all even when following the guide step by step.

**Comment by soojade** [comment]
I have the same problem.
Please update the document,Thanks.

**Comment by kwalrath** [comment]
See also https://github.com/dart-lang/site-webdev/issues/114.

**Comment by kwalrath** [comment]
(Leaving this bug here in case you want to partially fix it in the API doc comments.)

**Comment by matanlurey** [comment]
Closing for now. We can re-open if we should have specific updates.
