### ISSUE TITLE
Exception is thrown when upgrading to latest master

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/angular2#22]
EXCEPTION: Symbol("AppComponent") implements interfaces but does not declare them: Symbol("AfterContentChecked"), Symbol("AfterContentInit"), Symbol("AfterViewChecked"), Symbol("AfterViewInit"), Symbol("DoCheck"), Symbol("OnChanges"), Symbol("OnDestroy"), Symbol("OnInit"). See https://goo.gl/b07Kii for more info.

**Comment by matanlurey** [comment]
This only occurs AFAIK when you compile to dart2js but leave reflection enabled.

This isn't really a supported use case :-/ Worth prioritizing @kevmoo ?

**Comment by kevmoo** [comment]
I thought my reflection was DISABLED.

Do we know how to turn it off? I thought my config was correct here.

**Comment by matanlurey** [comment]
Any gist you can share?

One way you can tell is look how big the binary is :) Or add this to your main():

if (reflector.reflectionCapabilities is! NoReflectionCapabilities) {
  throw 'Oops! We shouldn't be using mirrors ever!';
}

**Comment by kevmoo** [comment]
I had my dart2js transformer running before (instead of after) the ng2 transformer. Fixing that fixed my issue.

**Comment by matanlurey** [comment]
@kevmoo Is it worth opening an issue for a simple `tool/validate_ng2.dart` that checks someone main.dart and pubspec to see if the transformers are setup correctly to help our external users?
