### ISSUE TITLE
Support for decorator @NgModule

### ISSUE THREAD

**Issue by xconic** [dart-lang/angular2#224]
Will the dart angular 2 version have support for the decorator @NgModule ? Or is there an alternative to this decorator, to group components, directives, services and pipes as a module?

**Comment by lejard-h** [comment]
Angular 2 Dart does not really need @NgModule,

If you want to use deferred loading, there is a nice article about it
https://medium.com/@matanlurey/lazy-loading-with-angular-dart-14f58004f988#.n36ah4wl8

**Comment by matanlurey** [comment]
Yep, this isn't planned at this time.

Please re-open if there are specific features you feel you need.
