### ISSUE TITLE
Move Angular2 transformer docs from Angular.js wiki

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/angular2#23]
https://github.com/angular/angular/wiki/Angular-2-Dart-Transformer

**Comment by matanlurey** [comment]
Maybe @jakemac53 (or Nate) should own the documentation (if they want to make any updates before we move it over), since they are also owning the long-term future of Angular's compiler stack.

**Comment by matanlurey** [comment]
@natebosch can you own this issue?

**Comment by matanlurey** [comment]
I think even if we just create a `/doc` (sort of where it was before anyway)
