### ISSUE TITLE
Global event in directive

### ISSUE THREAD

**Issue by jox81** [dart-lang/angular2#234]
Hello,

The directive documentation states : 
...
/// To listen to global events, a target must be added to the event name.
/// The target can be `window`, `document` or `body`.
...

But I tried to use global event target in a directive ;

`@Directive(
  selector: '[clickOutside]',
    host: const {
      '(document:click)': 'onClick(\$event.target)'
    }
)
class ClickOutsideDirective {
...
}`

but I've got an error telling me I can't use ':'

```
EXCEPTION: Template parse errors:
":" is not allowed in event names: document:click ("<!-- menu -->
[ERROR ->]<ul counting clickOutside>
    <li>Home</li>
    <li>News</li>
"): MenuComponent@1:0
```

Can u explain me the correct syntax ?

**Comment by matanlurey** [comment]
This is no longer supported as it encouraged dangerous patterns.

Fortunately you can just listen to events like this directly in your `@Component`:

```dart
import 'dart:async';
import 'dart:html';

class MenuComponent implements OnDestroy, OnInit {
  StreamSubscription _onDocumentClick;

  @override
  void ngOnInit() {
    _onDocumentClick = document.onClick.listen((e) {
      ...
    });
  }

  @override
  void ngOnDestroy() {
    _onDocumentClick.cancel();
  }
}
```

If you can point to to the documentation I'd be happy to update it.

**Comment by jox81** [comment]
ok, thank you for the idea.

Here is the documentation :
https://www.dartdocs.org/documentation/angular2/2.0.0-alpha.24/angular2.angular2/Directive/hostListeners.html


2016-12-20 4:12 GMT+01:00 Matan Lurey <notifications@github.com>:

**Comment by matanlurey** [comment]
We are now on 2.2.0 (non-Alpha/Beta), are you sure you aren't on an old version?

**Comment by jox81** [comment]
2.0.0, you're right, I'll update that !

2016-12-20 8:43 GMT+01:00 Matan Lurey <notifications@github.com>:
