### ISSUE TITLE
Can't run quickstart on my local environment.

### ISSUE THREAD

**Issue by HalShaw** [dart-lang/angular2#235]
Can't run quickstart on my local environment after 2016/12/14,before that,it worked.But today,when I run "npm install":
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.15

I searched on github,the results:
To add a new dependency do the following:
if you are on linux or windows, then use MacOS or ask someone with MacOS to perform the installation. This is due to an optional fsevents dependency that is really required on MacOS to get good performance from file watching.
— npm-shrinkwrap.readme.md

It means it can only run on MacOS?Someone help me,thanks.

**Comment by zoechi** [comment]
Are you sure this is the correct repository?
How is `npm` related to Dart?

**Comment by matanlurey** [comment]
I think you are looking for https://github.com/angular/angular.

**Comment by HalShaw** [comment]
Yes，it is，it worked a few days ago,it can't work yesterday,but it can work now.Strange,I don't know why,thanks anyway.
