### ISSUE TITLE
[API docs] broken link to template syntax

### ISSUE THREAD

**Issue by skybrian** [dart-lang/angular2#236]
https://webdev.dartlang.org/angular/api/angular2.common/NgIf-class

"See the Template Syntax section on ngIf for more details."

The link is broken. (It goes to https://webdev.dartlang.org/angular/api/docs/guide/template-syntax#ngIf which is a 404.)

**Comment by skybrian** [comment]
Template syntax can be found at: https://webdev.dartlang.org/angular/cheatsheet

**Comment by chalin** [comment]
@kwalrath - this is fixed; this link in question now goes to https://webdev.dartlang.org/angular/guide/template-syntax.html#ngIf

**Comment by kwalrath** [comment]
Confirmed that it works in https://webdev.dartlang.org/angular/api/angular2.common/NgIf-class.
