### ISSUE TITLE
Unhelpful Invalid Arguments(s) exception when missing selector from component 

### ISSUE THREAD

**Issue by guildcrest** [dart-lang/angular2#246]
**Angular Version** - 2.2.0

When any `@component` does not have a `selector:` the exception thrown is an unhelpful `Invalid Argument(s)` exception. This is different from the missing `template:` or `templateUrl:` where a `Component 'ComponentName' must have either 'template' or 'templateUrl" set.` exception is thrown. If an exception closer to the template exceptions was thrown it would help with debugging code.

To reproduce the error bootstrap to an empty component that does not have a `selector:` but does have its `template:`.

Link to non-minified stack trace: http://pastebin.com/qd8SBQjM

**Comment by chalin** [comment]
Cf. https://github.com/dart-lang/angular2/issues/60#issuecomment-248632901

**Comment by chalin** [comment]
@matanlurey - is `selector` _meant to be_ optional? If so, when do you expect that this will be supported?

cc @kwalrath

**Comment by chalin** [comment]
@matanlurey - Another comment about optional selectors that impacts **E2E testing**.

Currently all components in the doc samples have selectors, including those that only show up as views in router outlets. Such components show up in the DOM as elements named based on their selectors; e.g. `<my-crisis-center>`, and `<my-crises>` in
> ![screen shot 2017-03-15 at 3 32 16 pm](https://cloud.githubusercontent.com/assets/4140793/23973740/bc8ecf22-0994-11e7-939f-e046f8fea055.png)

If selectors are optional, then what will such components be named? In ngTS they use `<ng-component>`; e.g.
> ![screen shot 2017-03-15 at 3 32 54 pm](https://cloud.githubusercontent.com/assets/4140793/23973770/e66834d2-0994-11e7-8881-4f574c96e7ff.png)

Will this also be the case in AngularDart?
