### ISSUE TITLE
:host-context generates bad CSS

### ISSUE THREAD

**Issue by isoos** [dart-lang/angular2#248]
Same issue as https://github.com/angular/angular/issues/11466.

**Comment by enyo** [comment]
Am I missing something or is this rule unusable until this is fixed? Or is there a workaround for it?

**Comment by matanlurey** [comment]
@leonsenft Can you take a look at this?

**Comment by leonsenft** [comment]
This is a known issue and a fix should be landing shortly to address it.

**Comment by matanlurey** [comment]
Ping @leonsenft did this merge into MASTER here?

**Comment by leonsenft** [comment]
@matanlurey Not yet, still WIP.
