### ISSUE TITLE
Dependency issue between angular2_testing and angular2 beta.18 or higher.

### ISSUE THREAD

**Issue by ntaoo** [dart-lang/angular2#25]
Looks like angular2_testing is not upgraded. And the code is deleted from the repository.
On upgrading angular2 to beta.18 or higher, pub can't resolve the dependency with angular2_testing. 
So I'm hesitating to test and upgrade my public/private code with latest angular2.

I'd appreciate knowing the plan of angular2_testing to be upgraded, or perhaps deprecated or migrated to angular2?

**Comment by vikerman** [comment]
You should be able to use angular2_testing@2.0.0-beta.17 if you want it right now.

We will probably migrate it to this repo.

cc @juliemr @IgorMinar

**Comment by ferhatb** [comment]
Update: moving angular_testing.dart into main package, will land this week.
Updating your import 'package:angular2/testing/angular2_testing.dart';  and removing angular2_testing package from your pubspec.yaml will resolve issue.
