### ISSUE TITLE
Update View annotation info in doc comments

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/angular2#250]
Probably as a holdover from the days when at least one `@View` annotation was required, the [Component API page](https://webdev.dartlang.org/angular/api/angular2.core/Component-class) points to the [View API page](https://webdev.dartlang.org/angular/api/angular2.core/View-class)—but without any explanation.

The View API page has obsolete text:

> Each Angular component requires a single `@Component` and at least one `@View` annotation.

**Comment by matanlurey** [comment]
We should just deprecate/remove this annotation

**Comment by chalin** [comment]
`@View` has been [marked as deprecated](https://webdev-angular3-dartlang-org.firebaseapp.com/angular/api/angular2.core/View-class), so this can be closed.
