### ISSUE TITLE
Add viewProviders to directives

### ISSUE THREAD

**Issue by ranquild** [dart-lang/angular2#259]
Currently only components have `viewProviders` option in `@Component` annotation. We would like to have same option in `@Directive` as well so we can inject services that are scoped to this directive instance only, so they are not available to child components.

**Comment by matanlurey** [comment]
There is no such thing as a "view" for a `@Directive` - it has no template...

Wouldn't it just be `@Directive(providers: const [ ... ])`

**Comment by ranquild** [comment]
@matanlurey Am I right that dependencies that are declared in this annotation are not available elsewhere?

**Comment by matanlurey** [comment]
I mean they are only available in the sub-tree of the application, yes.

**Comment by ranquild** [comment]
@matanlurey We would like to declare dependencies in such way that they are not available to application sub-tree, as `viewProviders` do for components.

**Comment by matanlurey** [comment]
View providers are still available to the application sub-tree (i.e. their template).

Directives do not have a template, so they cannot possibly have view providers.

**Comment by ranquild** [comment]
@matanlurey So dependency that is declared in directive that is used in component A will not be available in component A child components?

**Comment by matanlurey** [comment]
They will be available to anything in the content - all directives are.

Only components have two types of children (view and content) where you can be specific.

**Comment by ranquild** [comment]
@matanlurey Got it - thanks a lot! I will close issue then.
