### ISSUE TITLE
Async pipe with stream does not seem to work

### ISSUE THREAD

**Issue by daniel-v** [dart-lang/angular2#260]
Example app: https://gist.github.com/daniel-v/4404bfceff16a6f8c68a9a295474fadd

My expectation is that whenever I add a new value to the stream, it will be displayed. Instead, nothing happens.

I found the source of the error. It's got to do with this line in async package: [StreamController.stream](https://github.com/dart-lang/sdk/blob/master/sdk/lib/async/stream_controller.dart#L459)

Together with AsyncPipes [identity check](https://github.com/dart-lang/angular2/blob/2.2.0/lib/src/common/pipes/async_pipe.dart#L72) things break. What happens is that the `obj` and `this._obj` will never be identical.

However, introducing a helper method would fix it.

```dart
  bool _maybeStreamIdentical(dynamic a, dynamic b) {
    if(a is Stream && b is Stream) {
      return identical(a, b) || a == b;
    } else {
      return identical(a, b);
    }
  }
```

**Comment by zoechi** [comment]
What about changing

```dart
Stream<String> get stream => _ctrl.stream;
```
to
```dart
Stream<String> get _stream;
Stream<String> get stream => _stream ??= _ctrl.stream;
```

**Comment by daniel-v** [comment]
That would work, I imagine. Either it has to be very well documented, that StreamControllers return a new Stream every time or make sure that it's not an issue. It's my 2 cent, that making sure that it's not an issue would space people some annoyment.

**Comment by zoechi** [comment]
> that making sure that it's not an issue would spare people some annoyment.

I basically agree, but if the stream is not intended to be used this way, then I think it shouldn't be "fixed" in Angular, but in documentation.

**Comment by johnpryan** [comment]
I'm trying to understand what the fix for this issue was. I have a `StreamController` with two separate streams created from it using `map`:

```dart
class FancyBloc {
  final StreamController<User> _sink;

  FancyBloc() : _sink = new StreamController.broadcast() {
  }

  Stream get firstName => _sink.stream.map((u) => u.firstName);
  Stream get lastName => _sink.stream.map((u) => u.lastName);

  ngOnInit() async {
    await new Future.delayed(new Duration(seconds: 1));
    _sink.add(new User()
      ..firstName = "Greg"
      ..lastName = "Gregorson");
  }
}

class User {
  String firstName;
  String lastName;
}
```

But in order to use asyncPipe, the result of calling `FancyBloc.firstName` and `FancyBloc.lastName` needs to return the same exact stream:

```dart
class FancyBloc {
  final StreamController<User> _sink;

  Stream firstName;
  Stream lastName;
  FancyBloc() : _sink = new StreamController.broadcast() {
    firstName = _sink.stream.map((u) => u.firstName);
    lastName = _sink.stream.map((u) => u.lastName);
  }

  ngOnInit() async {
    await new Future.delayed(new Duration(seconds: 1));
    _sink.add(new User()
      ..firstName = "Greg"
      ..lastName = "Gregorson");
  }
}

class User {
  String firstName;
  String lastName;
}
```

It would be nice if AsyncPipe could just assume that the `firstName` stream won't change and only listen to it once.
