### ISSUE TITLE
How to use "Module" in dart angular2 ?

### ISSUE THREAD

**Issue by itshakeel23** [dart-lang/angular2#263]
Hi

I am new in dart-angular2. Can someone guide how to use "Module" or provide an example tutorial?

Thanks

**Comment by zoechi** [comment]
There are no modules in Dart Angular. 
What are you trying to accomplish?
I think support question should be asked on StackOverflow, https://gitter.im/dart-lang/angular2, ...

**Comment by matanlurey** [comment]
Hi @itshakeel23 - if you have any other questions please file on SO :)
