### ISSUE TITLE
NgModel API doc has bad link to the live example

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/angular2#264]
A formatting problem in https://webdev.dartlang.org/angular/api/angular2.common/NgModel-class makes what's supposed to be live link look like this:

![image](https://cloud.githubusercontent.com/assets/2164483/22532932/a4d199ca-e89f-11e6-98ce-49d2febf17b8.png)

**Comment by kwalrath** [comment]
The fix for this is in #317. The updated API docs will go out when angular v3 stable ships.

**Comment by chalin** [comment]
Fixed, see https://webdev-angular3-dartlang-org.firebaseapp.com/angular/api/angular2.common/NgModel-class.
