### ISSUE TITLE
NgZone documentation has TypeScript sample code

### ISSUE THREAD

**Issue by leonsenft** [dart-lang/angular2#267]
https://webdev.dartlang.org/angular/api/angular2.core/NgZone-class

**Comment by kwalrath** [comment]
cc @chalin

**Comment by chalin** [comment]
I've been using https://github.com/dart-lang/site-webdev/issues/274 to track this work item for all TS samples that still appear in the API docs. Issue 274 will be tackled once https://github.com/dart-lang/site-webdev/issues/338 is finished --- which should be soon.

I'll keep this issue open as an angular-side (vs. docs-side) issue.

**Comment by chalin** [comment]
Fixed, see https://webdev-angular3-dartlang-org.firebaseapp.com/angular/api/angular2.core/NgZone-class
