### ISSUE TITLE
in latest v3.alpha angular2/core.dart doesn't seem to export `Injectable` and some other classes 

### ISSUE THREAD

**Issue by zoechi** [dart-lang/angular2#275]
```
import 'package:angular2/core.dart' show Injectable;
```
now causes an error (also `Host`, `Options`, `Inject`)

If this is intentional it should be mentioned in CHANGELOG.md

**Comment by kevmoo** [comment]
I can go back and look to see if this changed from previous releases using our crazy mirrors test.

I don't think having this in core will break anything. Will verify.

**Comment by zoechi** [comment]
Looks like this was fixed already.
