### ISSUE TITLE
Stop emitting ng_*.json

### ISSUE THREAD

**Issue by Tomucha** [dart-lang/angular2#276]
1) Take your favourite Angular2 project
2) run "pub build"
3) inspect the results in ./build/web

*Expected behaviour:*
"pub build" creates clean output which can be directly uploaded to the production environment.

*Observed behaviour:*
There are many files which are probably not needed in production (?): ng_meta.json, ng_summary.json ...

Please note that for example Google App Engine limits a number of files in app package in quotas. Not mentioning the amount of data which is transferred, distributed to CDN, archived, etc.

I understand that it might be hard to solve right know and that it depends on "pub" itself. For now, please provide some "safe cleanup script":

      rm `find . -name *.ng_*.json`

**Comment by zoechi** [comment]
AFAIK this is a transformer limitation, files can't be deleted once created.
I haven't found where I saw this being discussed.

**Comment by Tomucha** [comment]
You saw it here: https://plus.google.com/u/0/+TomasZverina/posts/gjigzCB2qY6

... but it still needs to be solved.

**Comment by Tomucha** [comment]
For example - we have this backend administration app in Angular2.Dart. We removed all probably unnecessary files from build/web:

     rm `find . -name *.ng_*.json`

... and final "war" package is now 18MB smaller.

**Comment by matanlurey** [comment]
There is no way to do this unfortunately with `barback` (pub transformers).

We're working on a new build process that won't have this limitation, though.

/cc @natebosch @jakemac53 

I'll leave this open as a tracker for our new build system.

**Comment by matanlurey** [comment]
Blocked by https://github.com/dart-lang/angular2/issues/404.
