### ISSUE TITLE
Using grid

### ISSUE THREAD

**Issue by kostonstyle** [dart-lang/angular2#287]
Hi dart team

Is there any grid components available for angular2dart?  

Thanks

**Comment by matanlurey** [comment]
Hi, thanks for filing an issue @kostonstyle.

We don't have any plan to provide grid components immediately, as we're not sure we can do so in a way that will perform well and not have code size implications. Obviously we welcome any community contributed package if someone feels strongly about it.

It might be nice to hear what you intend to build and what your needs are.

**Comment by matanlurey** [comment]
Ping @kostonstyle

**Comment by matanlurey** [comment]
I'm closing due to lack of response. Feel free to re-open if this becomes an issue.
