### ISSUE TITLE
Router.navigate Replace State

### ISSUE THREAD

**Issue by dergemkr** [dart-lang/angular2#292]
In writing a search component that live-updated the URL, I found that Router's `navigateByInstruction` and `navigateByUrl` both have optional parameters to replace the current state rather than pushing a new state to the browser's history. Why doesn't `navigate` have this option as well?

If it was not an intentional omission, I could create a PR with this change.

**Comment by matanlurey** [comment]
Thanks for filing, sorry for the delay in a response.

We're currently in the process of alpha-testing a new router, and we'll be pushing to GitHub/Pub shortly to get some external users to try it out. If you're blocked by this you might want to consider forking just the router components for a few weeks.
