### ISSUE TITLE
CSP issue

### ISSUE THREAD

**Issue by arcas0803** [dart-lang/angular2#30]
I´m just trying to create a chrome extension with angular 2 and this exception was thrown.
Exception: EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "default-src 'self' blob: filesystem: chrome-extension-resource:".

**Comment by matanlurey** [comment]
What version of Angular 2 Dart are you using?

**Comment by arcas0803** [comment]
2.0.0 beta18

**Comment by matanlurey** [comment]
Got it. We have that eval code removed in beta19/20, but I realize that hasn't been pushed to pub yet.

If you use HEAD here on github does that problem still persist?

**Comment by matanlurey** [comment]
We just pushed beta19, give it a try @arcas0803

**Comment by arcas0803** [comment]
thanks a lot

**Comment by arcas0803** [comment]
Its working well

**Comment by Kleak** [comment]
When i created a very basic angular2 app i have this error. But everything is working apparently.
```
Refused to execute inline script because it violates the following Content Security Policy directive: "default-src 'self' blob: filesystem: chrome-extension-resource:". Either the 'unsafe-inline' keyword, a hash ('sha256-ivwTIKBvUSOffGqvz0ii2BQccechlRLBfQg8F57XF5A='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.
```
it appear to happen when this script is injected into index.html:
```
window['ngSetProperty'] = function(el, prop, value) {
          el[prop] = value;
        }
        window['ngGetProperty'] = function(el, prop) {
          return el[prop];
        };
        window['ngHasProperty'] = function(el, prop) {
          return prop in el;
        };
        window['ngSetGlobalVar'] = function(path, value) {
          var parts = path.split('.');
          var obj = window;
          var i;
          for (i = 0; i < (parts.length - 1); i++) {
            var name = parts[0];
            if (obj.hasOwnProperty(name)) {
              obj = obj[name];
            } else {
              obj = obj[name] = {};
            }
          }
          obj[parts[parts.length - 1]] = value;
        }
```

Do you have more information ?
