### ISSUE TITLE
code_builder.dart - _writeImportExports – order is not stable, causes flaky tests

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/angular2#302]
https://travis-ci.org/dart-lang/angular2/jobs/209843079#L753

Could we do a sort here to make sure this is stable?

**Comment by matanlurey** [comment]
Sure, I can take this. FWIW it is always stable internally..

@natebosch @jakemac53  - `barback` specific issue?

**Comment by jakemac53** [comment]
Barback definitely runs things differently, but that is most likely not a bug.

It seems like maybe the ng2 compiler is relying on execution order of some async tasks, which happens to be consistent in bazel due to how things are ran but is not in barback?

**Comment by matanlurey** [comment]
Do we have ordering logic somewhere I can copy, or should I just do `uri.toString()` for now?

**Comment by natebosch** [comment]
I think the `toString()` is probably fine to use.

**Comment by kevmoo** [comment]
Yup. We only care about stable.

**Comment by matanlurey** [comment]
Fix underway internally, will merge up here.

**Comment by kevmoo** [comment]
sweet!

**Comment by kevmoo** [comment]
Seems not fixed - https://travis-ci.org/dart-lang/angular2/jobs/216538805#L278

@matanlurey ??

**Comment by matanlurey** [comment]
Hmm. I'll take a look tomorrow.

**Comment by kevmoo** [comment]
I think fixed now...

SDK issue

**Comment by kevmoo** [comment]
Nope https://travis-ci.org/dart-lang/angular2/jobs/219046312
