### ISSUE TITLE
ngSwitchWhen --> ngSwitchCase

### ISSUE THREAD

**Issue by chalin** [dart-lang/angular2#307]
Switch statements have **cases**, and so it seems natural to name an Angular switch case as `ngSwitchCase`.

(Angular TS made the switch from `ngSwitchWhen` to `ngSwitchCase`. Eliminating unnecessary differences between ngTS and ngDart is also a reason to rename the directive.)

**Comment by matanlurey** [comment]
I'll discuss with the team offline, but my guess is this will be after 3.0 final if at all.

**Comment by chalin** [comment]
Closed by https://github.com/dart-lang/angular2/commit/ec016dc3d8f487b04a4f868f95f9fedc2452a703 via #308
