### ISSUE TITLE
Allow to configure a `NodeValidator` or `TreeNodeSanitizer` for `[innerHtml]="..."`

### ISSUE THREAD

**Issue by zoechi** [dart-lang/angular2#31]
```html
<span [innerHtml]="someHtml">
```

currently results in

> Removing disallowed attribute <DIV xmlns="http://www.w3.org/1999/xhtml">

My Workaround is currently using a custom directive

```dart
import 'dart:html' show Element, NodeTreeSanitizer;

import 'package:angular2/core.dart'
    show Directive, ElementRef, Input, OnChanges, SimpleChange;

@Directive(selector: '[safeInnerHtml]')
class SafeInnerHtml implements OnChanges {
  ElementRef _elRef;
  SafeInnerHtml(this._elRef);

  @Input()
  String safeInnerHtml;

  @override
  void ngOnChanges(Map<String, SimpleChange> changes) {
    (_elRef.nativeElement as Element).setInnerHtml(this.safeInnerHtml,
        treeSanitizer: NodeTreeSanitizer.trusted);
  }
}
```

Maybe similar to https://angular.io/docs/ts/latest/api/platform-browser/index/DomSanitizationService-class.html

**Comment by sanfordredlich** [comment]
+1, I have the same problem.

**Comment by matanlurey** [comment]
@ferhatb is this something that the new security API is supposed to handle?

If yes, can we get a 1/2 page document on safe HTML/URLs we can publish?

**Comment by matanlurey** [comment]
Ping @ferhatb :)

**Comment by zoechi** [comment]
Shouldn't that be added to the CHANGELOG.md?

**Comment by matanlurey** [comment]
We'll add it - I think I need a bit more work on this to get it something noteworthy.
