### ISSUE TITLE
Initial binding not done with `OnPush`

### ISSUE THREAD

**Issue by zoechi** [dart-lang/angular2#328]
When this component is added by the router 
```dart
@Component(
  selector: 'xxx',
  template: '<div>{{'foo'}}</div>',
  changeDetection: ChangeDetectionStrategy.OnPush
)
component MyComponent{}
```
the resulting DOM is `<div></div>` (without `foo`).
Calling `ChangeDetectorRef.markForCheck()` renders `foo`.
I think this should be rendered without the need to explicitly mark the component for change detection.

`AppComponent` containing the `<router-outlet>` also has   `changeDetection: ChangeDetectionStrategy.OnPush` set.

**Comment by matanlurey** [comment]
By definition `OnPush` components don't check themselves when created as an optimization. In this case though, it's probably safe for the _router_ to mark all created components `markForCheck`. I'll make that change.

**Comment by matanlurey** [comment]
Discussed this offline. We don't support the root component being `OnPush` right now.

I'll update the documentation to reflect as such, it will not be fixed in 3.0.0, and we don't have any immediate plans to change the behavior.

**Comment by zoechi** [comment]
Great, thanks for the feedback. Never saw this mentioned anywhere that the root component is not supposed to be set to `OnPush`.

**Comment by zoechi** [comment]
What about an exception if the root component is set to `OnPush`?
