### ISSUE TITLE
angular 2 and polymer dart

### ISSUE THREAD

**Issue by hentoesch** [dart-lang/angular2#33]
it seems that angular 2 switched from dart:js to package:js with version beta.19.
polymer dart still seems to use dart:js.

not surprisingely, this breaks angular2 <-> polymer interop in many ways.

**Comment by matanlurey** [comment]
Can you clarify what you mean? AFAIK, `dart:js` and `package:js` don't invalidate each other.

**Comment by hentoesch** [comment]
i have a polymer element that wraps iron-list.
i pass a pretty nested dart object, describing the iron-list  format, to to this element.

dart object:

  DataRowModel orderRows = new DataRowModel([
    new Paragraph([
      new DataRow([
        new DataColumn('name', style: "font-weight: bold"),
        new DataColumn('contact'),
        new DataColumn('phone' ),
        new DataColumn('pickupDate',
            style: "float: right", callback: dateFormat)

where callback "dateFormat" is a static function.
there are diifferent callbacks in the class hierarchy - it works in beta.18.

in beta.19 i get "xxx.get$callback is not a function" for the different callbacks.

**Comment by matanlurey** [comment]
If this is the same issue as #32 can we please close this one to avoid confusion?

**Comment by hentoesch** [comment]
of course.
