### ISSUE TITLE
User needs help with DynamicComponentLoader

### ISSUE THREAD

**Issue by nchesnokov** [dart-lang/angular2#331]
After dynamic load componet ngForm  onSubmit form data is empty.
No dynamic load componenton ngForm Submit form data is not empty.

What is the program error?

mport 'dart:html';
import 'dart:convert' show JSON;
import 'package:angular2/angular2.dart';
import 'package:angular2/core.dart';
import 'package:angular2/platform/browser.dart';
import 'package:angular2//src/compiler/runtime_compiler.dart';
import 'package:gsrp5webclient/service_component.dart';
import 'package:angular2/src/core/linker/dynamic_component_loader.dart';
import 'package:angular2/src/core/linker/component_resolver.dart';
import 'package:gsrp5webclient/login.dart';
import 'package:gsrp5webclient/modelapi.dart';

@Component(
    selector: 'my-app',
    directives: const [ServiceComponent])
    //template: '<my-login></my-login>')
class AppComponent  implements OnInit, AfterViewInit {
	final String title = "Hello App";
	ServerAPi srv;
	bool reconnectScheduled;
	AppComponent(){
	this.srv = new ServerAPI();
	this.srv.Connect('ws:/localhost:8100/ws',30);
	ModelAPI model = new ModelAPI('bc.users');
	var count = model.Count(cond:['user','=','root'],context:{'lang':'ru_RU','tz':'UTC+03'});
	print('count:${count}');
	var search = model.Search(cond:['user','=','root'],context:{'lang':'ru_RU','tz':'UTC+03'},offset:1,limit:2);
	print('search:${search}');
	var read = model.Read([1,2,3]);
	print('read:${read}');
	var unlink = model.Unlink([1,3]);
	print('unlink:${unlink}');
	var create = model.Create([{'user':'root','password':'admin'},{'user':'guest','password':'user'}]);
	print('create:${create}');
	var write = model.Write([{'id':1,'user':'root','password':'admin'},{'id':99,'user':'guest','password':'user'}]);
	print('write:${write}');
	var modify = model.Modify([{'user':'root','password':'admin'},{'id':99,'user':'guest','password':'user'}]);
	print('modify:${modify}');
	}

	void ngAfterViewInit(){
	ComponentResolver compiler = new ReflectorComponentResolver();
	DynamicComponentLoader dcl =  new DynamicComponentLoaderImpl(compiler);
	ReflectiveInjector injector = ReflectiveInjector.resolveAndCreate([]);
	dcl.load(ServiceComponent,injector).then(
	(ComponentRef comp){
	window.console.log(comp);
	querySelector('my-app').append(comp.location.nativeElement);
	print('ngAfterInit:');
	});
	}
	void ngOnInit(){

	}

}

**Comment by matanlurey** [comment]
Hi @nchesnokov 

Is it possible to make a simple minimal reproduction on Github and share with us? I'm not going to be able to make much progress based off a partial code sample here.

**Comment by matanlurey** [comment]
Ping @nchesnokov

**Comment by nchesnokov** [comment]
github repo https://github.com/neo5g/gsrp5.git
directory webclient/gsrp5webclient
installed to dart-sdk 1.23 & dartium 1.23
pub get
pub server --port 8101 or start.sh
