### ISSUE TITLE
`pub get` failed on 3.0.0-beta

### ISSUE THREAD

**Issue by furrary** [dart-lang/angular2#332]
Steps to reproduce:

1. `stagehand web-angular-simple`
2. Change the dependencies to 
```
dependencies: 
  angular2: 3.0.0-beta
````
3. `pub get`
```
Loading source assets...
A transformer imported unknown package "quiver" (in "package:quiver/iterables.dart").
exit code 0
```

If I add `angular2_components` as another dependency, `pub get` will pass
but `pub serve` with dart2js will throw
```
Uncaught TypeError: Cannot read property 'add$1' of undefined
```

OS: Windows 10
Dart SDK: 1.22.0

**Comment by matanlurey** [comment]
We are working on this for 3.0.0-beta+1

As a workaround add the following to your pubspec.yaml:

```dart
dependency_overrides:
  quiver:
```

**Comment by daniel-v** [comment]
`pub upgrade` on the app resolved this for me without the `dependency_overrides`.
The error you see in browser is likely because of this: #337

**Comment by kevmoo** [comment]
Fixed with beta+1
