### ISSUE TITLE
dartfmt fails for  1.23.0-dev.11.5

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/angular2#333]
See https://travis-ci.org/dart-lang/angular2/jobs/218587280#L276

Files are unformatted:
lib/src/common/forms/validators.dart
lib/src/compiler/provider_parser.dart
lib/src/compiler/view_compiler/view_builder.dart
lib/src/testing/internal.dart
lib/src/testing/test_injector.dart
test/meta/types_test.dart

**Comment by kevmoo** [comment]
@matanlurey @ferhatb This is fun.

Do we want to skip this until we sync Dart SDK versions internally?

**Comment by matanlurey** [comment]
I vote skip until we have consistent SDK versions.

**Comment by kevmoo** [comment]
Closing out this issue. Will open another issue to re-enable dartfmt tests

**Comment by kevmoo** [comment]
Actually, this was fix! Never mind...
