### ISSUE TITLE
_compView_1.rootEl is null

### ISSUE THREAD

**Issue by zoechi** [dart-lang/angular2#335]
I'm not sure if this is a bug in my application or in Angular.
Any idea what could cause that?
I'm not aware of changes in this area of the application in a while.

![image](https://cloud.githubusercontent.com/assets/405837/24745457/1b5260fa-1ab6-11e7-83bb-0a4de4d384b0.png)

This is in 3.0.0-beta and 3.0.0-alpha+1

**Comment by zoechi** [comment]
Changing back to `angular2: 3.0.0-alpha` fixed it.

**Comment by zoechi** [comment]
@matanlurey any hint why this is closed as invalid?
The application works in 3.0.0-alpha but breaks in newer Angular versions

**Comment by matanlurey** [comment]
I read this wrong. It is still broken in beta?

**Comment by zoechi** [comment]
Perhaps I should have explained better, but I didn't know what's going on or if I'd be able to gather more information later. 
My application throws because `compView1` is `null` (in line 631) in `3.0.0-beta` and `3.0.0-alpha+1` but returning to `3.0.0-alpha` fixed it.

**Comment by matanlurey** [comment]
Ok, thank you. I guess a minimum reproduction might be difficult?

Or an obsfucated version of your component that still reproduces?

**Comment by zoechi** [comment]
I'll try to provide more information tomorrow

**Comment by zoechi** [comment]
I updated to 3.0.0-beta.1

Not I get
```js
      ViewDropdownMenuItemComponent0$2: function(parentView, parentIndex) {
        var t1, t2;
        t1 = document;
        this.rootEl = t1.createElement("");
        t1 = $.ViewDropdownMenuItemComponent0_renderType;
        if (t1 == null) {
          t1 = H.S($.appViewUtils._appId) + "-";
          t2 = $.AppViewUtils__nextCompTypeId;
          $.AppViewUtils__nextCompTypeId = t2 + 1;
          t2 = new A.RenderComponentType(t1 + t2, "asset:fhir_webui/lib/webui/dropdown_menu/menu_item_component.dart class DropdownMenuItemComponent - inline template", C.ViewEncapsulation_2, C.List_empty, null, null, null, false);
          $.ViewDropdownMenuItemComponent0_renderType = t2;
          t1 = t2;
        }
        this.setupComponentType$1(t1);
```
where `        this.rootEl = t1.createElement("");` causes an exception

```
"EXCEPTION: InvalidCharacterError: Failed to execute 'createElement' on 'Document': The tag name provided ('') is not a valid name.
STACKTRACE: 
Error: Failed to execute 'createElement' on 'Document': The tag name provided ('') is not a valid name.
    at HTMLDocument.createElement (<anonymous>:1:1545)
    at ViewDropdownMenuItemComponent0$2 (http://localhost:63342/fhir_designer/web/designer.dart.js:164839:26)
    at Object.ViewDropdownMenuItemComponent0$ (http://localhost:63342/fhir_designer/web/designer.dart.js:164865:14)
    at ViewFormEditorComponent4.build$0 (http://localhost:63342/fhir_designer/web/designer.dart.js:117667:16)
    at ViewFormEditorComponent4.dart.AppView.create$2 (http://localhost:63342/fhir_designer/web/designer.dart.js:27773:21)
    at ViewFormEditorComponent4.create$2 (http://localhost:63342/fhir_designer/web/designer.dart.js:29519:21)
    at TemplateRef.createEmbeddedView$1 (http://localhost:63342/fhir_designer/web/designer.dart.js:28742:14)
    at NgFor__applyChanges_closure.call$3 (http://localhost:63342/fhir_designer/web/designer.dart.js:23229:45)
    at DefaultIterableDiffer.forEachOperation$1 (http://localhost:63342/fhir_designer/web/designer.dart.js:25865:16)
    at NgFor._applyChanges$1 (http://localhost:63342/fhir_designer/web/designer.dart.js:23195:17)
ORIGINAL EXCEPTION: InvalidCharacterError: Failed to execute 'createElement' on 'Document': The tag name provided ('') is not a valid name.
```
The component has an attribute selector

```dart
@Component(
  selector: 'property-dropdown-menu',
  providers: const <dynamic>[
    const Provider(MenuProvider, useExisting: PropertyDropdownMenuComponent),
  ],
  directives: const <dynamic>[
    FORM_DIRECTIVES,
    GlyphComponent,
    InsideWindowPopupSizeProviderDirective,
    MaterialFabComponent,
    materialInputDirectives,
    MaterialButtonComponent,
    MaterialPopupComponent,
    NgFor,
    PopupSourceDirective,
  ],
  styleUrls: const <String>['dropdown_menu_component.css'],
  templateUrl: 'dropdown_menu_component.html',
)
class PropertyDropdownMenuComponent implements MenuProvider {
```
The same component is used multiple times in the whole application, but only here I get the exception.
It's used twice within the same component (where I get above error). The other instance immediately before this one works fine.

I'll try to find a way for a smaller reproduction, but it doesn't look like an easy task.

**Comment by matanlurey** [comment]
@zoechi:

> The component has an attribute selector

What do you mean? I don't see one above.

/cc @ferhatb

**Comment by ferhatb** [comment]
Hi zoechi, when you pub build, do you see error/warning that you need to have tag in selector ? New build can't create a component without a proper tag.

**Comment by zoechi** [comment]
Sorry, I posted the wrong component's code. I meant to post 
```dart
@Component(
  selector: '[menuItem]',
  providers: const <dynamic>[],
  directives: const <dynamic>[
    MaterialRippleComponent,
  ],
  host: const <String, String>{
    '[class.mdl-menu__item]': 'true',
    '[attr.tabindex]': '-1',
  },
  template: '''
<ng-content></ng-content>
<material-ripple></material-ripple>
''',
)
class DropdownMenuItemComponent {
```

**Comment by ferhatb** [comment]
The selector has to contain tag name now. 'div[menuItem],[menuItem]' is one possibility. Ideally you want selector: 'menu-item'.

We are updating compiler that will shortly give you build error pointing to class DropdownMenuItemComponent and [menuItem] with proper error message.

**Comment by zoechi** [comment]
"The selector has to contain tag name now."
You mean this is mandatory? Any reason why?
