### ISSUE TITLE
Travis CI not running on master branch

### ISSUE THREAD

**Issue by alorenzen** [dart-lang/angular2#34]
Looking at [travis ci](https://travis-ci.org/dart-lang/angular2), it appears that it is only running for the  travis_cl branch, and not the master branch.

**Comment by alorenzen** [comment]
@kevmoo

**Comment by kevmoo** [comment]
Known issue. We had a bit of tweaking to do to get these files added to the github push.

This all should work in our next push to master.

CC @ferhatb

**Comment by kevmoo** [comment]
Fixed in https://github.com/dart-lang/angular2/commit/3b9f0d6714ea661b95cac07f27a05174b8e0fce5
