### ISSUE TITLE
Make transformer to not process all css files

### ISSUE THREAD

**Issue by luisvt** [dart-lang/angular2#352]
The transformer is now processing all the css files in the project, this could cause some issues if the project contains files with incorrect css.

This issue raised with `ng_bootstrap` which uses `bootstrap_sass` which generate an incopatible css for `csslib`. Even though the solution was to add the css files to the `$exclude` option in the transformers, I don't think is good idea the transformer process all the css files. This could lead in other different behavior.

**Comment by natebosch** [comment]
The transformer was always processing all css files in the project, the difference is the transformer updates no longer accept some css that used to work.

@jakemac53 - can you think of any good way for angular to structure things such that only .css files referenced by components get used as inputs?

**Comment by jakemac53** [comment]
It gets tricky to make something that works in pub and bazel... but in a pub only world you could just use the Dart files as primary inputs and read the annotations to figure out which css files to read in.

**Comment by leonsenft** [comment]
@matanlurey What info is missing here?

My understanding is that the transformer should only process CSS files referenced in `@Component` annotations via `styleUrls` as @jakemac53 is suggesting. Is there any reason this would be an issue for Pub or Bazel?

**Comment by matanlurey** [comment]
It's not possible to read a file to determine what files to further read, unfortunately. The most we could do is perhaps only process files that end in .ng.css for example.

**Comment by jakemac53** [comment]
ya, I think using $include or $exclude are probably the best options to reduce code fragmentation between pub/bazel.

**Comment by leonsenft** [comment]
Okay. Unfortunately `$include` and `$exclude` doesn't solve the problem for projects wishing to exclude files in another project, but the reason why that's an issue is unrelated.

**Comment by leonsenft** [comment]
@matanlurey Should this be closed as won't fix, seeing as the limitation is outside Angular?

**Comment by leonsenft** [comment]
@luisvt See my latest comment on #348. I'm working to relax the parser so you won't see these issues.
