### ISSUE TITLE
docs: move cheatsheet *.md files to site-webdev

### ISSUE THREAD

**Issue by chalin** [dart-lang/angular2#360]
As agreed to with @kwalrath.

https://github.com/dart-lang/site-webdev/issues/571 is the corresponding webdev-side issue.

**Comment by kwalrath** [comment]
We'll do this after v3 goes gold.

**Comment by matanlurey** [comment]
@chalin @kwalrath Can this be closed? Still relevant?

**Comment by chalin** [comment]
Sorry, I forgot to link the PR: this issue is fixed by #373

**Comment by chalin** [comment]
Fixed by #373, which is now closed, so closing this issue too.
