### ISSUE TITLE
The initial classes of the main component are removed during bootstrap

### ISSUE THREAD

**Issue by alextekartik** [dart-lang/angular2#366]
Angular 3.0.0

I created a basic example based on the Angular template where I only added a class on the main component

    <my-app class="my_initial_class">Loading...</my-app>

The class `my_initial_class` is removed during  bootstrap (which was not the case with Angular 2.0.0). The following startup code:

```
main() async {
  print("before bootstrap: ${document.querySelector("my-app").classes}");
  await bootstrap(AppComponent);
  print("after bootstrap: ${document.querySelector("my-app").classes}");
}
```

printing the following in the console:

```
before bootstrap: my_initial_class
after bootstrap: _nghost-ocy-1
```
showing that the class disappears. To note that this is not the case for any other component. It only happens for the main one.

Source code here: https://github.com/alextekartik/dart-test/tree/master/angular_main_component_class_test

**Comment by leonsenft** [comment]
@ferhatb I think this might related to the change you made with `bootstrap`, mind taking a look?

**Comment by leonsenft** [comment]
It turns out this is intentional, if you wish to apply an initial class to the bootstrapped element, you can do so in the component itself.

```dart
@Component(
  template: 'my-app',
  host: const {
    'class': 'my_initial_class',
  },
)
class MyApp {}
```

Is this solution suitable for your situation?

It's worth mentioning the `Element.id` property is preserved by bootstrapping if that helps.

**Comment by alextekartik** [comment]
Ok thanks. Yes i found another workaround by putting the class on the body element. I have a situation where I have 2 applications sharing the same code (so here your solution does not apply) but not the same html entry point so I was using a class on the initial component for some global css styling. I personally think that it is an odd intention (why preserving the id and not the class) but I don't think it will be showstopper for anybody to have such restriction as long as it gets documented somewhere. Thanks for confirmation

**Comment by leonsenft** [comment]
I agree it seems strange but replacing the element altogether was done in an effort to unify how components are built (regardless of whether they're the root or not), which in turn will simplify and reduce the generated code. Preserving the Element.id was done so there's still an absolute sure way to locate the application root. See 908022b909c15b136dbb6c5e0d6b4e1b8f8edd37.
