### ISSUE TITLE
Dynamic component loader no binding variable

### ISSUE THREAD

**Issue by nchesnokov** [dart-lang/angular2#375]
Variable not binding after load component dynamic from form control
Static componet load is ok.
github repo https://github.com/neo5g/gsrp5.git
directory webclient/gsrp5webclient
installed to dart-sdk 1.23 & dartium 1.23
pub get
pub server --port 8101 or start.sh

**Comment by matanlurey** [comment]
Hi @nchesnokov - I'll need a bit more minimum reproduction to be useful here.

At the very least please share:

- A full stack trace
- A link to the code where this error occurs

etc.

**Comment by zoechi** [comment]
I think
```dart
ReflectiveInjector injector = ReflectiveInjector.resolveAndCreate([LoginComponent]);
	dcl.load(LoginComponent,injector).then(
```
should just be
```dart
//ReflectiveInjector injector = ReflectiveInjector.resolveAndCreate([LoginComponent]);
	dcl.load(LoginComponent /*,injector*/).then(
```
I wouldn't expect this to solve your problem though.
Please provide the informatino what binding you expect to update with what value.
