### ISSUE TITLE
Define behavior of {{x}} v {{x.toString()}}

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/angular2#382]
I don't fully understand the code where I saw this, but I was helping a coworker debug something.

We found that

```
  <a href="{{thing.url}}">
```

didn't render a graph properly, but

```
  <a href="{{thing.url}}/">
```

did. Notice the `/`. Now of course my first reaction was that the url itself needed the `/`, clearly. But...

```
  <a href="{{thing.url.toString()}}">
```

(no slash) did work. 

`thing.url` was a special "trusted URL."

We also found that

```
  <a [href]="thing.url"> <!-- did not work -->
  <a [href]="thing.url.toString()"> <!-- did work -->
```

Unless I'm mistaken, shouldn't these behaviors all be the same?

This strikes me as an over aggressive optimization -- change detect `thing.url` instead of change detecting `thing.url.toString()` in the mustache, even though `thing.url.toString()` may change when `thing.url` doesn't.

Which might mean its a bug, and might mean its intended behavior.

lastly: obviously the href of a URL doesn't render a graph. I'm not sure how the graph was loading, I'm wondering if maybe the addition of a binding watching `{{thing.url}}` could affect other bindings elsewhere (if they share a watcher, but the watcher changes to some kind of "lowest-common-denominator"/"greatest-common-factor" type of way which might have affected what I assume is a different binding somewhere else that actually rendered the graph.

**Comment by hterkelsen** [comment]
Can you provide some more details? Is `thing.url` a `SafeUrl` from [`DomSanitizationService#bypassSecurityTrustUrl`](https://github.com/dart-lang/angular2/blob/master/lib/src/security/dom_sanitization_service.dart#L85)?

For interpolation (the `{{}}` syntax) we actually do check if the `toString` output changes, but for normal change detection we don't. However, for `SafeUrl` interpolation just returns the `SafeUrl` back.

Can you give a minimal repro case?

**Comment by MichaelRFairhurst** [comment]
looks like cl 156087089

**Comment by hterkelsen** [comment]
We solved this offline. The problem was the `thing.url` was a `SafeResourceUrl`, not a `SafeUrl`. It worked with the added slash because interpolation called `toString()` on `thing.url` before passing it to the sanitizer.
