### ISSUE TITLE
3.1.0+ w/ use_analyzer: Can't use external packages.

### ISSUE THREAD

**Issue by jodinathan** [dart-lang/angular2#390]
Hi,

I imported NgModel: 
import 'package:angular2/angular2.dart' show NgModel;

added it to the directives:
@Component(directives: const [NgModel])

However, the error still occurs: 
ParseErrorLevel.FATAL: Can't bind to 'ngModel' since it isn't a known native property or known directive. Please fix typo or add to directives list.

This does not happen with NgClass and NgIf.

**Comment by matanlurey** [comment]
Could you include your entire `.dart`, `.html`, and `pubspec.yaml`, if possible?

You can email me at matanl@google.com if it is private and you'd prefer not to post publicly.

**Comment by matanlurey** [comment]
In the example you emailed me there is no `NgModel` in your `address_generic.dart` file.

Everyplace you use `ngModel` in your `.html` template you must declare it in `directives: [ ... ]` in the corresponding `.dart` file. Please re-open this issue if you feel that there is something else going on.

**Comment by matanlurey** [comment]
Re-opened, as discussed on Gitter.

Using is trying to use `package:intl` and `package:http`, both of which are not AngularDart libraries, but we still try and import `http.template.dart` and `intl.template.dart`. I believe @alorenzen has a fix for this internally (yet to submit).

**Comment by zoechi** [comment]
Seems to be the same issue dart-lang/pub#1611

**Comment by natebosch** [comment]
Does our multi-phase approach solve this? I'm a bit surprised to see it's a problem at all...

cc @jakemac53 
If this multi-phase approach fixes this we might need to unblock this in `build_runner`.
