### ISSUE TITLE
Speed up travis runs

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular2#393]
We'd like to be quicker about syncing changes to/from Google. Travis is quite slow, though.

Suggestions:

- [ ] Only test against `stable` and `dev`, no pinned versions. 

(Reduces the number of tests run by 1/3)

- [ ] Use new experimental travis feature to de-dupe requests of PR versus Push

- [ ] Consider disabling Firefox tests. They are really slow (5x slower than anything else)

- [ ] Consider using Bazel to run the test suites on Travis instead of pub (Even viable?)

/cc @kevmoo, @natebosch

**Comment by natebosch** [comment]
For using bazel we'd have a few blockers:

- Test rules aren't all externalized yet and have been tricky
- We'd have to externalize the (very complex) BUILD file and end up using an unsupported approach to rules_dart

Long term I think both of these are solvable, but we shouldn't count on it in the short term.
