### ISSUE TITLE
The link for angular_components code-lab in README is broken 

### ISSUE THREAD

**Issue by furrary** [dart-lang/angular2#414]
<https://codelabs.developers.google.com/codelabs/your-first-angulardart-web-app> shows `Forbidden 403`.

Adding a `/` at the end of the URL can fix the problem.

<https://codelabs.developers.google.com/codelabs/your-first-angulardart-web-app/>

The link on <https://webdev.dartlang.org/angular/> is broken for the same reason.

**Comment by matanlurey** [comment]
Thank you! Care to send a PR? I'll merge it immediately @furrary

**Comment by furrary** [comment]
Sorry, I really want to help out, but I'm a total beginner and really don't know how to send a PR. 😢

**Comment by kwalrath** [comment]
Strangely, those URLs work for me. But I believe you. I can fix this bug.

**Comment by kwalrath** [comment]
I've reported this issue against the codelab infrastructure. Thanks very much for letting us know about it, @furrary!

**Comment by x1ddos** [comment]
This should be fixed now on the codelabs website.
Thanks again for noticing.

**Comment by kwalrath** [comment]
The codelabs team has quickly responded with a workaround that makes URLs like https://codelabs.developers.google.com/codelabs/your-first-angulardart-web-app work. (But it doesn't hurt to have / there.)

**Comment by furrary** [comment]
<https://codelabs.developers.google.com/codelabs/your-first-angulardart-web-app> is now working for me
