### ISSUE TITLE
Use global event listener instead of local

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular2#441]
From @ferhatb:

> Support  `(^focus)="handler"` for most common dom events.
>
> Focus gets tracked globally for you without adding expensive listener on each element

**Comment by leonsenft** [comment]
We tried this and it was a performance regression for a number of internal benchmarks, without seeing gains for any others. Local testing did show it reduced registration time in the presence of many listeners though, so perhaps our benchmarks are too micro focused.

**Comment by matanlurey** [comment]
Closing for now.
