### ISSUE TITLE
Router stops working forever once one routing error happens

### ISSUE THREAD

**Issue by hpmv** [dart-lang/angular2#457]
If the routerOnActivate function throws, or some other routing error happens, the router will stop functioning for further routing requests.

If I replace the following function

```
  Future<dynamic> navigateByInstruction(Instruction instruction,
      [bool _skipLocationChange = false, bool _replaceState = false]) {
    if (instruction == null) {
      return _resolveToFalse;
    }
    return this._currentNavigation = this._currentNavigation.then((_) {
      this._startNavigating(instruction.toLinkUrl());
      return this._afterPromiseFinishNavigating(
          this._navigate(instruction, _skipLocationChange, _replaceState));
    });
  }
```
with
```
...
    return this._currentNavigation = this._currentNavigation.whenComplete(() {
...
```

then the router can work again. Is this intended behavior or should we make the above fix?

**Comment by zoechi** [comment]
AFAIK that's expected behavior. You need to catch and handle exceptions close to where they are caused. After an uncaught exception the application is in an inconsistent state and continuing usually won't make sense.

You can also use `async`/`await` with `try`/`catch`/`finally`

**Comment by matanlurey** [comment]
Yes, we aren't able to recover from a thrown exception. Sorry about that.
