### ISSUE TITLE
Add `ngOutletContext` attribute to `NgTemplateOutlet` similar to TS

### ISSUE THREAD

**Issue by luisvt** [dart-lang/angular2#46]
Please add `ngOutletContext` attribute to `NgTemplateOutlet`.

In TS version you can see how this attribute is being implemented:

https://github.com/angular/angular/blob/2.0.0-rc.5/modules/%40angular/common/src/directives/ng_template_outlet.ts#L38

this attribute allows to change the context of the outlet, which allows to use the component internal scope
instead the scope of the current component

``` html
<template [ngTemplateOutlet]="templateRefExpression"
          [ngOutletContext]="objectExpression">
</template>
```

I already create a similar directive into `ng_bootstrap`, this directive is `BsTemplateOutlet` you can find the source code here:

https://github.com/dart-league/ng_bootstrap/blob/develop/lib/components/template_outlet/bs_template_outlet.dart

**Comment by matanlurey** [comment]
@ferhatb What do you think of this change? Make sense?

**Comment by ferhatb** [comment]
Hi Luis makes sense to add. Would you like to contribute and send us PR?

**Comment by luisvt** [comment]
I could translate code from TS version, however the unit test will fail.

**Comment by matanlurey** [comment]
That's fine, we can tackle the unit test (working on our new testing story now).

**Comment by luisvt** [comment]
Ok, I'll do it at night

**Comment by matanlurey** [comment]
👍

**Comment by luisvt** [comment]
I created the pull request #50, please take a look

**Comment by rvaleev** [comment]
What should be done to move this forward?

**Comment by MichaelRFairhurst** [comment]
Please ping me if this gets solved, its something we could analyze.

**Comment by matanlurey** [comment]
No action in ~4 months.

Closing for now as we don't have any internal requirements and no PR was merged.

**Comment by luisvt** [comment]
How can we create `grid` or `typeahead` component without it?

**Comment by dentra** [comment]
it is really needed

**Comment by zoechi** [comment]
It's not difficult to create your own `MyTemplateOutlet` directive from `NgTemplateOutlet` and add a `ngOutletContext`.
I did it but couldn't find the time to polish it enough for a pull request (add tests, ...)
