### ISSUE TITLE
Unable to set boolean attributes with dev compiler

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/angular2#463]
Steps to reproduce:

1. Use a component with a boolean attribute (e.g. material-expansionpanel)
2. Bind the attribute to a false value (e.g. `showSaveCancel={{myFalseValue}}`)
3. run `pub-serve`  with the dev compiler
4. observe that the component fails to render.  The generated dart file tries to set a boolean attribute to `false`:

In Dartium:

![screen shot 2017-06-20 at 5 57 11 pm](https://user-images.githubusercontent.com/1145719/27362245-ea690a5e-55e1-11e7-93cc-c456706e3111.png)

In Chrome: (using the dev compiler)
<img width="1223" alt="screen shot 2017-06-20 at 5 57 43 pm" src="https://user-images.githubusercontent.com/1145719/27362256-fecad432-55e1-11e7-9d42-0dd6d10a5d47.png">

**Comment by TedSander** [comment]
So this is actually working as intended according to angular/ddc. Text interpolation {{}} will always produce a String. So `showSaveCancel={{myFalseValue}}` will be setting the boolean type to a String which is an error in strong mode. To set a typed value on an attribute you need to use the [] syntax. `[showSaveCancel]="myFalseValue"`.

Now many angular_components provide an API to be more forgiving with either boolean or string values, but it looks like material_expansion_panel is not using that pattern.

**Comment by johnpryan** [comment]
Thanks for the quick response!
