### ISSUE TITLE
type confusion when input type is number

### ISSUE THREAD

**Issue by Matrix-Zhang** [dart-lang/angular2#54]
if add ngModel for input when type is number, the model will auto transform to num even through the model is string type

**Comment by ferhatb** [comment]
Are you expecting the directive to check model's existing value type and use string? What if the model value is null ?

**Comment by matanlurey** [comment]
I believe this is WAI @Matrix-Zhang - we don't know your existing value type and assume that `type="number"` means you want a `num`.

**Comment by Matrix-Zhang** [comment]
For example: 
`<input id="xxx" type="number" ngModel="yyy">`
the xxx.value is string type, but yyy will transform to number type...

**Comment by matanlurey** [comment]
ngModel is smart about what type it thinks you want.

You can always use `(change)="inputChanged($event)"` in the HTML if you want to capture the raw event yourself and do something custom / only use strings.
