### ISSUE TITLE
Unused variable in test function after TimerWrapper facade removal

### ISSUE THREAD

**Issue by b-strauss** [dart-lang/angular2#55]
I just stumbled upon this after browsing recent commits.

This function:

https://github.com/dart-lang/angular2/blob/af290b020bc4ed975f73547823315f2e8e3cf10a/test/common/forms/directives_test.dart#L45

seems to not use the timeout parameter properly. From what I can tell, it needs to be passed to the Duration.

https://github.com/dart-lang/angular2/commit/af290b020bc4ed975f73547823315f2e8e3cf10a#diff-b00a2e16fd7528fd8939e9cf6ac0debf

**Comment by kevmoo** [comment]
Good find. Want to try and create a pull request to fix this?

CC @ferhatb @matanlurey

**Comment by b-strauss** [comment]
Yes, I'd like to do that.

**Comment by matanlurey** [comment]
Closed by #57.
