### ISSUE TITLE
Using package:intl with Angular Dart

### ISSUE THREAD

**Issue by gedw99** [dart-lang/angular2#62]
question about  integration with tooling ?

https://pub.dartlang.org/packages/intl

https://pub.dartlang.org/packages/intl_translation

The way it plugs into the Google Translate APi is great.

Is this integrated into Angular2 though ?

also the github URLs are wrong. Not sure how to contact the package authours..

**Comment by matanlurey** [comment]
I'm going to look a little into how we can provide a better package:intl experience.

**Comment by joeblew99** [comment]
OK good to know it's on the quasi roadmap.

I guess I can leave this open.

**Comment by matanlurey** [comment]
Please leave it open 😀 - open to discussing with the community what they would like to see!

**Comment by sestegra** [comment]
In my current projects, I'm using **intl** and **intl_translation** packages to manage i18n.
My projects are covering DartVM, webdev with angular2 and coming soon Flutter.

In order to have the same framework for all kind of target (browser, server, mobile), **intl** package should be the core part of angular2 i18n as well.

**Comment by joeblew99** [comment]
@sestegra nice.

i agree. I too am developing for flutter, web, server.

**Comment by matanlurey** [comment]
Just an update: This is out of scope for 4.0.0. We are planning a bit of package re-organization that should make this easier for outside folks to contribute.

**Comment by matanlurey** [comment]
Another update: We are working on a way to make this easier, at least.

Please review and give feedback on https://github.com/dart-lang/angular2/issues/374.

**Comment by matanlurey** [comment]
Due to #374, we don't have any plans to immediately add i18n support in the template.
