### ISSUE TITLE
Migrate documentation comment code samples from typescript to dart

### ISSUE THREAD

**Issue by ben4ever** [dart-lang/angular2#63]
If you `git grep -A 10 '```typescript'` you still find a number of documentation comments which contain typescript code samples which haven't been ported to dart yet.

**Comment by matanlurey** [comment]
Thanks for filing. We definitely still need some example cleanup

**Comment by kulshekhar** [comment]
I've submitted a couple of PRs (#95 & #101) with these changes. If anyone else is planning to work on this as well, you might want to use  

```
git grep -A 10 -E '@Component\(\{|@Directive\(\{|directives: \[|providers \['
```

or something similar to identify more documentation with snippets of typescript code.

**Comment by kwalrath** [comment]
@chalin and @thso and I will be working on a subset of the API docs for the next few weeks. I can coordinate our work with @ben4ever, @kulshekhar, and @b-strauss. (Anyone else? Obviously, I'll also talk to @kevmoo & @matanlurey, and keep @ferhatb informed of our progress.)

**Comment by kulshekhar** [comment]
We should probably have a tracker for this with a list of files that are being worked on, to prevent duplication of effort.

**Comment by kwalrath** [comment]
I was thinking the same thing. I have a spreadsheet that I'll make world-readable. And I'll create an issue so this work is more visible.
