### ISSUE TITLE
b21: dart:js_util dependecy exception

### ISSUE THREAD

**Issue by frankpepermans** [dart-lang/angular2#65]
After upgrading to b21, running the app in Dartium, the console reads:

The requested built-in library is not available on Dartium.'package:angular2/src/platform/browser/browser_adapter.dart': error: line 5 pos 1: library handler failed
import 'dart:js_util' as js_util;
^: package:angular2/src/platform/browser/browser_adapter.dart

**Comment by frankpepermans** [comment]
After upgrading to the Dartium that comes with v1.20, I no longer get this issue.

Perhaps the release notes need to mention the minimum required version?

**Comment by matanlurey** [comment]
@kevmoo: Should we set an SDK constraint?

**Comment by kevmoo** [comment]
@matanlurey Yup. Already did it internally.

**Comment by kevmoo** [comment]
> @matanlurey Yup. Already did it internally.

or not. We should.

**Comment by kevmoo** [comment]
This will be fixed when we land the commit corresponding to MOE=133018217

**Comment by Ne4istb** [comment]
@frankpepermans where can i find Dartium from v1.20? I've set up dart and Dartium from dev channel but it doesn't work still 😭

**Comment by kevmoo** [comment]
Dartium v1.20 should be included in the latest dev channel release

What's your `dart --version`?

**Comment by kevmoo** [comment]
...or have you tried upgrading to Angular beta.22?

**Comment by Ne4istb** [comment]
Dart VM version: 1.20.0-dev.10.0 (Thu Sep 29 09:47:27 2016) on "macos_x64"
Dartium version: 45.0.2454.104 (64-bit)

I've tried both beta.22 and beta.21

**Comment by Ne4istb** [comment]
@kevmoo Thanks, i've fixed the problem. My shortcut was pointing on stable version still instead of dev.
