### ISSUE TITLE
b21: removing animation

### ISSUE THREAD

**Issue by frankpepermans** [dart-lang/angular2#66]
I understand the choice to remove the animation directives,
according to the release notes, a new, more Darty solution will be provided at some point.

However I was depending on the animation directives, b21 left me with no alternative what so ever.

Please consider to properly deprecate code over releases.

**Comment by matanlurey** [comment]
So some good news - it's unlikely anything else will be killed (that was some of the last bit of the cruft). Animation wasn't working properly internally, and we figured pretending to support it would cause more harm for our users than removing from the API for the time being.

I understand your pain though, we'll be more selective going forward.

**Comment by frankpepermans** [comment]
No problem, I was able to replace it rather quickly, I'm all for dropping the bad parts where needed
