### ISSUE TITLE
b21: Creating style elements for ViewEncapsulation.Native

### ISSUE THREAD

**Issue by dentra** [dart-lang/angular2#73]
Prior to b21 every style elements was created with DOM.createStyleElement but with b21 for ViewEncapsulation.Native it creates with AppView.createStyleElement that simple uses document.createElement('STYLE').

I am using Angular and Polymer together so in my application I need to use document.createElement('STYLE', 'custom-style'). I'm extends from BrowserDomAdapter and override createStyleElement with this logic. But now it is working only for ViewEncapsulation.Emulated and ViewEncapsulation.None.

It is possible to override AppView and use custom or maby in AppView.createStyleElement you can use DOM.createStyleElement insted of call to document.createElement?

**Comment by matanlurey** [comment]
@ferhatb: Due to recent changes?

**Comment by matanlurey** [comment]
We made a decision to prefer speed and a simple code path to supporting overriding how style elements are created in this particular case. What does `custom-style` do @dentra?

**Comment by dentra** [comment]
@matanlurey `custom-style` is extension of the native `<style>` element that allows defining styles in the main document that can take advantage of several special features of [Polymer's](https://www.polymer-project.org) styling system. In html it looks like `<style is="custom-style">` and can be created by calling document.createElement with `custom-style` as second parameter. 

But this is only a part of problem, also I need to add additional `include` attribute to `<style>` elements (example: `<style is="custom-style" include="shared-style">`), so at this moment `DOM.createStyleElement` is prefferd way for me to override `<style>` element creation logic, but I am will happy to consider any other options.

Please take a look at [Polymer's](https://www.polymer-project.org) documentation https://www.polymer-project.org/1.0/docs/api/custom-style for details.

**Comment by matanlurey** [comment]
Ack, thanks. Ok, I found you a workaround for now:

In `angular2/lib/src/platform/dom/shared_styles_host.dart` there is a global variable called `sharedStyleHost` that we initialize at bootup. You can add your own, i.e.:

```dart
class PolymerCompatibleSharedStylesHost extends SharedStylesHost {
  ...
}

void main() {
  sharedStyleHost = new PolymerCompatibleSharedStylesHost();
}
```

**Comment by dentra** [comment]
@matanlurey unfortinally overriding `SharedStylesHost` is not an option because at `addHost` I can't get any style element - it created after this call.

```dart
  ShadowRoot createViewShadowRoot(dynamic hostElement) {
    assert(componentType.encapsulation == ViewEncapsulation.Native);
    var nodesParent;
    Element host = hostElement;
    nodesParent = host.createShadowRoot();
    sharedStylesHost.addHost(nodesParent); // <--- this might be overriden
    List<String> styles = componentType.styles;
    int styleCount = styles.length;
    for (var i = 0; i < styleCount; i++) {
      nodesParent.append(createStyleElement(styles[i])); // <--- can't get this style element to extend them
    }
    return nodesParent;
  }

  StyleElement createStyleElement(String css) {
    StyleElement el = document.createElement('STYLE');
    el.text = css;
    return el;
  }
```

Also I am not sure that we need to duplicate every style elements in `DomSharedStylesHost.onStylesAdded` previosly created for Emulated scope elements.

**Comment by dentra** [comment]
@matanlurey have you any update?

**Comment by ferhatb** [comment]
Hi sorry for the breakage. We are moving createStyleElement from AppView to SharedDomStyleHost so you can subclass and override. You'll have to create initializeSharedStyleHost() that will run before bootstrap. ETA: 9/29. Please manually patch app_view on your devbox until we land this.
