### ISSUE TITLE
Explore batching Style additions

### ISSUE THREAD

**Issue by natebosch** [dart-lang/angular2#75]
When creating a tree of components we repeatedly add `<style>` tags to the document and the browser has to do some work for each one. We should check whether we can batch these up and append them once.

Open questions:
- Does it actually reduce work that the browser has to do?
- Is batching appends until the next Event Loop adequate?

**Comment by matanlurey** [comment]
We need to be careful about how this could cause stabilization to be inaccurate.

i.e. a component says it's done, but styles do not yet exist.

**Comment by natebosch** [comment]
With my initial experiment there is a pretty big difference between batching until the next microTask and batching until the next event loop. With microTask batching I get only a few components styles gathered before flushing and I can't see any difference while it renders. With event loop batching I get an entire page rendered before flushing and I can briefly see the unstyled components before it flushes. I have not yet measured the performance impact of either.

**Comment by matanlurey** [comment]
Owch. FOUC should be avoided, yeah.

**Comment by natebosch** [comment]
I haven't been able to find any evidence that this has a performance impact.
