### ISSUE TITLE
will angular 2 dart support the new FormControl for model driven  forms?

### ISSUE THREAD

**Issue by hentoesch** [dart-lang/angular2#79]
as angular 2 ts has gone 2.0 now, i found out that there is a new way of handling model driven forms,
and the old "ngFormControl" is deprecated.

will angular2/dart eventually also support the new version?

**Comment by matanlurey** [comment]
Good question. We're working on a new forms module internally right now, probably as a separate `package:angular2_forms`, versus part of the core package. I am not sure about exact API usage right now, but we're pretty excited about it.

Short answer is "probably no".
