### ISSUE TITLE
Recover cheatsheet sources

### ISSUE THREAD

**Issue by chalin** [dart-lang/angular2#8]
Cheatsheet sources (`*.md` files) used to be under `docs/cheatsheet`, but this folder no longer exists. Without this we can't build the cheatsheet for angular.io/dart.

cc @kwalrath

**Comment by kwalrath** [comment]
The cheatsheet appears in the docs at https://angular.io/docs/dart/latest/guide/cheatsheet.html. Without `docs/cheatsheet`, that page will be blank.

A temporary workaround is to copy in the b17 docs directory while generating the angular.io site, but that's a fragile solution.

**Comment by matanlurey** [comment]
Looks like we should  have this back now.

**Comment by kwalrath** [comment]
For some reason, they were under `doc/cheatsheet`. I had to move them to `docs/cheatsheet` to generate the docs.

@chalin where should they be?

**Comment by chalin** [comment]
@kevmoo wrote https://github.com/dart-lang/angular2/pull/40#issuecomment-240855189:
> FYI: I've moved docs to doc to follow package conventions.

So I'll update our build scripts.
