### ISSUE TITLE
sanitizeHtmlInternal throws in Firefox and Chrome for element embed and object

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/angular2#80]
Get a TypeError - type 'JavaScriptFunction' is not a subtype of type 'Node'

Repro: `pub run test -p firefox,chrome test/security/html_sanitizer_test.dart`

**Comment by kevmoo** [comment]
See pub run test -p firefox,chrome test/security/html_sanitizer_test.dart

**Comment by matanlurey** [comment]
@kevmoo Can we close this?

**Comment by kevmoo** [comment]
@matanlurey – I'm guessing we don't want our `sanitizeHtmlInternal` method to randomly crash, right?

**Comment by matanlurey** [comment]
Sorry this has gotten ignored quite a bit. I think it's unlikely we will get to it immediately, given it doesn't seem any clients have run into this.
