### ISSUE TITLE
Can't retrieve attributes of the top-level component

### ISSUE THREAD

**Issue by AdrienGuichard** [dart-lang/angular2#87]
We need to pass arguments from the server, to the Angular2 component.

I cannot manage to pass via attributes like I managed to do with AngularJS.

the host page contains:
```
<scrollable-table
             [table-header-url]="${g.createLink(action: 'itemTableHeader')}"
             [table-data-url]="${g.createLink(action: 'itemTableData', params: [offset: 0, rowCount: 100])}"
             [number-of-row-displayed]="5">Loading...</scrollable-table>
```

the component:
```
@Component(
    selector: 'scrollable-table',
    inputs: const ['number-of-row-displayed', 'action-load-table-url'],
    styleUrls: const ['cybertable_component.css'],
    templateUrl: 'cybertable_component.html')
class ScrollableTable implements OnInit {
  @Input('action-load-table-url')
  String actionLoadTableUrl;
  @Attribute('number-of-row-displayed')
  String numberOfRowDisplayed;
  String dataUrl;

  ngOnInit() {
    print("${actionLoadTableUrl} ${numberOfRowDisplayed}");
}
```

the Chrome console do print:

> null null

whatever I tried (putting @Attribute, @Input, changing cases on attribute names ...) the properties are not initialized and no errors are printed.

Is it possible to get attributes from the server?
Is there a documentation telling how to process?

I am using 

> angular2: 2.0.0-beta.21

Thanks for your support!
Adrien

**Comment by AdrienGuichard** [comment]
ok, I managed to get attributes reading:
[(https://angular.io/docs/dart/latest/guide/attribute-directives.html)]

the document

**Comment by zoechi** [comment]
See also http://stackoverflow.com/questions/37155082/initialize-angular-2-component-with-attribute/37155204#37155204
