### ISSUE TITLE
b22 analyzer error with ng2 transformers

### ISSUE THREAD

**Issue by frankpepermans** [dart-lang/angular2#98]
Having upgraded to b22 and after also upgrading to SDK 1.19.1,
I get the following transformer errors:

```
[DirectiveProcessor]:
  Failed with 2 errors
Error 1: line 94, column 9 of lib\src\compiler\view_compiler\compile_pipe.dart and parts: Expected an identifier
        )
        ^
Error 2: line 94, column 9 of lib\src\compiler\view_compiler\compile_pipe.dart and parts: Positional arguments must occur before named arguments
        )
        ^
[DirectiveProcessor on angular2|lib/src/compiler/view_compiler/compile_pipe.dart]:
Error in lib/src/compiler/view_compiler/compile_pipe.dart and parts: Expected an identifier

Error in lib/src/compiler/view_compiler/compile_pipe.dart and parts: Positional arguments must occur before named arguments
```

They point to trailing comma usage in code pages, an example below where it throws after the last comma:

```
getPropertyInView(
          this.instance.prop("transform"),
          callingView,
          this.view,
          forceCast: true,
)
```

**Comment by kevmoo** [comment]
Any ideas, @ferhatb , @matanlurey ?

**Comment by frankpepermans** [comment]
Solved it, some other dependency kept analyzer from updating to the min required version,
I've added analyzer: 0.28.1 to my pubspec file and was able to solve the conflict from then on.

In short, analyzer: 0.28.x is also a min requirement

**Comment by kwalrath** [comment]
@frankpepermans, could you give a little more info on "They point to trailing comma usage in code pages"? Where did you see that?

Thanks!

**Comment by frankpepermans** [comment]
@kwalrath see the stack trace I posted, compile_pipe.dart inside the angular source code has a trailing comma at line 94

Eg

void foo (a, b, c, ) 

Where c has a trailing comma

**Comment by kwalrath** [comment]
Ah, OK. I thought "code pages" meant docs.

**Comment by dentra** [comment]
Unfortunally analyzer 0.28.x is not compatible with Polymer 1.0.0-rc.18 thar required 0.27.0 strongly. It is Polymer problem?

**Comment by kevmoo** [comment]
Yeah, this is really a polymer issue – https://github.com/dart-lang/polymer-dart/issues/716
